"""Lexer generated by OpenLexer with start condition support."""

from enum import Enum, auto
from dataclasses import dataclass
from typing import Optional, Dict, Tuple

class TokenType(Enum):
    EOF = auto()
    ERROR = auto()
    NUMBER = auto()
    IDENTIFIER = auto()
    PLUS = auto()
    MINUS = auto()
    TIMES = auto()
    DIVIDE = auto()
    LPAREN = auto()
    RPAREN = auto()


class StartCondition(Enum):
    INITIAL = 0


@dataclass
class Token:
    type: TokenType
    text: str
    pos: int
    line: int = 1
    column: int = 1

# Maps rule_index -> (token_type or None, new_state or None)
RULE_ACTIONS: Dict[int, Tuple[Optional[TokenType], Optional[StartCondition]]] = {
    0: (TokenType.NUMBER, None),
    1: (TokenType.IDENTIFIER, None),
    2: (TokenType.PLUS, None),
    3: (TokenType.MINUS, None),
    4: (TokenType.TIMES, None),
    5: (TokenType.DIVIDE, None),
    6: (TokenType.LPAREN, None),
    7: (TokenType.RPAREN, None),
    8: (None, None),
    9: (TokenType.ERROR, None),
}

# DFA transition tables per start condition
TRANSITIONS: Dict[StartCondition, Dict[int, Dict[str, int]]] = {
    StartCondition.INITIAL: {
        0: {'\\': 2, '0': 3, ' ': 7, 'F': 1, '`': 2, 'z': 1, 'b': 1, 'y': 1, '\x1a': 2, 't': 1, '2': 3, 'A': 1, '\x0e': 2, '\x02': 2, 'c': 1, 'n': 1, 'h': 1, 'j': 1, '4': 3, '\x05': 2, 'C': 1, 'Z': 1, '\x7f': 2, 'l': 1, '\x01': 2, '\x06': 2, '?': 2, 'W': 1, '\x16': 2, 'V': 1, '}': 2, 'O': 1, '/': 4, '\'': 2, '\n': 11, '*': 6, '8': 3, 'B': 1, 'M': 1, ',': 2, 'G': 1, '\x12': 2, '1': 3, '>': 2, 'r': 1, '\x19': 2, '+': 5, '\x1f': 2, '<': 2, '&': 2, '\x0c': 2, '_': 2, '|': 2, '!': 2, '\x1d': 2, 'x': 1, '\x1b': 2, '^': 2, 'q': 1, '\x04': 2, '\x10': 2, '\x13': 2, '\x08': 2, ';': 2, '\x03': 2, 'J': 1, 'I': 1, ']': 2, '-': 8, 'P': 1, '=': 2, '\x1c': 2, '"': 2, '\x0f': 2, '9': 3, ')': 9, 'p': 1, 'S': 1, 'K': 1, 'e': 1, 'R': 1, '\x00': 2, '\x18': 2, 'm': 1, '~': 2, '3': 3, 'u': 1, ':': 2, 'L': 1, '[': 2, 'D': 1, 'd': 1, 'Q': 1, 'o': 1, '\x11': 2, 'w': 1, '%': 2, 's': 1, '\x14': 2, '\x15': 2, '\x07': 2, 'a': 1, 'T': 1, '\x1e': 2, 'E': 1, '6': 3, '7': 3, '.': 2, '#': 2, 'U': 1, '\x0b': 2, 'f': 1, 'g': 1, '(': 10, '5': 3, 'k': 1, '\t': 7, 'Y': 1, '\x17': 2, 'X': 1, 'v': 1, 'i': 1, '@': 2, '{': 2, '\r': 2, '$': 2, 'H': 1, 'N': 1, },
        1: {'W': 13, 's': 13, 'r': 13, 'z': 13, 'U': 13, 'u': 13, 'F': 13, 'I': 13, 'E': 13, 'B': 13, 'A': 13, 'g': 13, 'v': 13, 'T': 13, 'G': 13, 'P': 13, 'o': 13, 'p': 13, 'f': 13, 'n': 13, 'D': 13, 'c': 13, 'w': 13, 'L': 13, 'R': 13, 'X': 13, 'b': 13, 't': 13, 'k': 13, 'a': 13, 'Y': 13, 'e': 13, 'y': 13, 'H': 13, 'j': 13, 'q': 13, 'm': 13, 'x': 13, 'C': 13, 'V': 13, 'J': 13, 'i': 13, 'K': 13, 'O': 13, 'h': 13, 'd': 13, 'Z': 13, 'S': 13, 'M': 13, 'Q': 13, 'l': 13, 'N': 13, },
        2: {},
        3: {'7': 12, '9': 12, '1': 12, '6': 12, '4': 12, '2': 12, '8': 12, '3': 12, '0': 12, '5': 12, },
        4: {},
        5: {},
        6: {},
        7: {' ': 11, '\n': 11, '\t': 11, },
        8: {},
        9: {},
        10: {},
        11: {' ': 11, '\n': 11, '\t': 11, },
        12: {'5': 12, '1': 12, '0': 12, '4': 12, '6': 12, '9': 12, '2': 12, '3': 12, '8': 12, '7': 12, },
        13: {'u': 13, 'V': 13, 'F': 13, 'C': 13, 's': 13, 'Z': 13, 'J': 13, 'S': 13, 'v': 13, 'G': 13, 'e': 13, 'L': 13, 'A': 13, 'P': 13, 'Q': 13, 'I': 13, 'y': 13, 'i': 13, 'n': 13, 'o': 13, 'd': 13, 'z': 13, 'X': 13, 'D': 13, 'm': 13, 'U': 13, 't': 13, 'N': 13, 'E': 13, 'T': 13, 'K': 13, 'l': 13, 'R': 13, 'j': 13, 'W': 13, 'q': 13, 'f': 13, 'Y': 13, 'r': 13, 'B': 13, 'w': 13, 'x': 13, 'b': 13, 'c': 13, 'a': 13, 'g': 13, 'k': 13, 'h': 13, 'M': 13, 'H': 13, 'O': 13, 'p': 13, },
    },
}

# Accepting states: condition -> {state_id: rule_index}
ACCEPTING: Dict[StartCondition, Dict[int, int]] = {
    StartCondition.INITIAL: {
        1: 1,
        2: 9,
        3: 0,
        4: 5,
        5: 2,
        6: 4,
        7: 8,
        8: 3,
        9: 7,
        10: 6,
        11: 8,
        12: 0,
        13: 1,
    },
}

class Lexer:
    def __init__(self, input_str: str):
        self.input = input_str
        self.pos = 0
        self.line = 1
        self.column = 1
        self.condition = StartCondition.INITIAL
        self._condition_stack: list = []

    def begin(self, condition: StartCondition):
        """Switch to a new start condition."""
        self.condition = condition

    def push_state(self, condition: StartCondition):
        """Push current condition and switch to new one."""
        self._condition_stack.append(self.condition)
        self.condition = condition

    def pop_state(self):
        """Pop and restore previous condition."""
        if self._condition_stack:
            self.condition = self._condition_stack.pop()

    def next_token(self) -> Token:
        while self.pos < len(self.input):
            start = self.pos
            start_line = self.line
            start_column = self.column
            state = 0
            last_accepting_rule = -1
            last_accepting_pos = start

            trans_table = TRANSITIONS.get(self.condition, {})
            accept_table = ACCEPTING.get(self.condition, {})

            while self.pos < len(self.input):
                c = self.input[self.pos]
                state_trans = trans_table.get(state, {})
                next_state = state_trans.get(c, -1)
                if next_state == -1:
                    break
                state = next_state
                self.pos += 1
                # Track line/column
                if c == '\n':
                    self.line += 1
                    self.column = 1
                else:
                    self.column += 1

                if state in accept_table:
                    last_accepting_rule = accept_table[state]
                    last_accepting_pos = self.pos

            if last_accepting_rule >= 0:
                self.pos = last_accepting_pos
                action = RULE_ACTIONS.get(last_accepting_rule, (TokenType.ERROR, None))
                token_type, new_condition = action
                text = self.input[start:last_accepting_pos]

                # Handle state change
                if new_condition is not None:
                    self.condition = new_condition

                if token_type is None:  # Skip
                    continue
                return Token(token_type, text, start, start_line, start_column)
            else:
                # No match - return error token for single char
                self.pos = start + 1
                if self.input[start] == '\n':
                    self.line += 1
                    self.column = 1
                else:
                    self.column += 1
                return Token(TokenType.ERROR, self.input[start:self.pos], start, start_line, start_column)

        return Token(TokenType.EOF, '', self.pos, self.line, self.column)

    def tokenize(self):
        """Generator that yields all tokens."""
        while True:
            token = self.next_token()
            yield token
            if token.type == TokenType.EOF:
                break
