[build]
target = "web/index.html"
dist = "dist"
no_sri = true

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = true
[serve.headers]
"Cross-Origin-Opener-Policy" = "same-origin"
"Cross-Origin-Embedder-Policy" = "credentialless"
