//! Code generation for table-driven lexers.

use crate::error::Result;
use crate::lexgen::dfa::Dfa;
use crate::lexgen::nfa::Nfa;
use crate::lexgen::rules::{LexerSpec, RuleAction};
use std::collections::HashMap;

pub enum TargetLanguage {
    C,
    Java,
    Python,
}

/// Generates a lexer from a DFA (legacy single-pattern mode).
pub fn generate_lexer(dfa: &Dfa, lang: TargetLanguage) -> Result<String> {
    match lang {
        TargetLanguage::C => generate_c_simple(dfa),
        TargetLanguage::Java => generate_java_simple(dfa),
        TargetLanguage::Python => generate_python_simple(dfa),
    }
}

/// Generates a full lexer from a lexer specification with start conditions.
/// Builds separate DFAs for each start condition for optimal performance.
pub fn generate_lexer_from_spec_with_conditions(
    spec: &LexerSpec,
    lang: TargetLanguage,
) -> Result<String> {
    // Build DFAs for each start condition
    let mut dfas: HashMap<String, Dfa> = HashMap::new();

    for condition in spec.start_conditions.keys() {
        let nfa = Nfa::from_lexer_spec_for_condition(spec, condition)?;
        let dfa = Dfa::from_nfa(&nfa)?;
        dfas.insert(condition.clone(), dfa);
    }

    match lang {
        TargetLanguage::C => generate_c_with_conditions(&dfas, spec),
        TargetLanguage::Java => generate_java_with_conditions(&dfas, spec),
        TargetLanguage::Python => generate_python_with_conditions(&dfas, spec),
    }
}

/// Generates a full lexer from a DFA and lexer specification (multi-token mode).
/// Legacy API - does not support start conditions properly.
pub fn generate_lexer_from_spec(
    dfa: &Dfa,
    spec: &LexerSpec,
    lang: TargetLanguage,
) -> Result<String> {
    // If spec has only INITIAL condition, use the simple path
    if spec.start_conditions.len() <= 1 {
        match lang {
            TargetLanguage::C => generate_c_full(dfa, spec),
            TargetLanguage::Java => generate_java_full(dfa, spec),
            TargetLanguage::Python => generate_python_full(dfa, spec),
        }
    } else {
        // Use the new condition-aware generator
        generate_lexer_from_spec_with_conditions(spec, lang)
    }
}

// =============================================================================
// Full multi-token lexer generation with start conditions
// =============================================================================

fn generate_python_with_conditions(
    dfas: &HashMap<String, Dfa>,
    spec: &LexerSpec,
) -> Result<String> {
    let mut code = String::new();

    code.push_str("\"\"\"Lexer generated by OpenLexer with start condition support.\"\"\"\n\n");
    code.push_str("from enum import Enum, auto\n");
    code.push_str("from dataclasses import dataclass\n");
    code.push_str("from typing import Optional, Dict, Tuple, List\n\n");

    // Token type enum
    code.push_str("class TokenType(Enum):\n");
    code.push_str("    EOF = auto()\n");
    code.push_str("    ERROR = auto()\n");
    let mut seen_tokens = std::collections::HashSet::new();
    seen_tokens.insert("EOF".to_string());
    seen_tokens.insert("ERROR".to_string());
    for rule in &spec.rules {
        match &rule.action {
            RuleAction::Token(name) | RuleAction::TokenAndBegin(name, _) => {
                let upper = name.to_uppercase();
                if seen_tokens.insert(upper.clone()) {
                    code.push_str(&format!("    {} = auto()\n", upper));
                }
            }
            _ => {}
        }
    }
    code.push_str("\n\n");

    // Start condition enum
    code.push_str("class StartCondition(Enum):\n");
    for (idx, cond) in spec.start_conditions.keys().enumerate() {
        code.push_str(&format!("    {} = {}\n", cond, idx));
    }
    code.push_str("\n\n");

    // Token dataclass
    code.push_str("@dataclass\n");
    code.push_str("class Token:\n");
    code.push_str("    type: TokenType\n");
    code.push_str("    text: str\n");
    code.push_str("    pos: int\n");
    code.push_str("    line: int = 1\n");
    code.push_str("    column: int = 1\n\n");

    // Rule to action mapping (token type and optional state change)
    code.push_str("# Maps rule_index -> (token_type or None, new_state or None)\n");
    code.push_str(
        "RULE_ACTIONS: Dict[int, Tuple[Optional[TokenType], Optional[StartCondition]]] = {\n",
    );
    for (idx, rule) in spec.rules.iter().enumerate() {
        let (token_str, state_str) = match &rule.action {
            RuleAction::Token(name) => (
                format!("TokenType.{}", name.to_uppercase()),
                "None".to_string(),
            ),
            RuleAction::TokenAndBegin(name, state) => (
                format!("TokenType.{}", name.to_uppercase()),
                format!("StartCondition.{}", state),
            ),
            RuleAction::Skip => ("None".to_string(), "None".to_string()),
            RuleAction::Begin(state) => ("None".to_string(), format!("StartCondition.{}", state)),
            RuleAction::Error => ("TokenType.ERROR".to_string(), "None".to_string()),
            RuleAction::Code(_) => {
                // Code actions are handled separately in the action switch
                ("None".to_string(), "None".to_string())
            }
        };
        code.push_str(&format!("    {}: ({}, {}),\n", idx, token_str, state_str));
    }
    code.push_str("}\n\n");

    // Generate range-based transition tables for each start condition
    code.push_str("# DFA range-based transition tables per start condition\n");
    code.push_str("# Format: {state: [(start_codepoint, end_codepoint, target_state), ...]}\n");
    code.push_str(
        "RANGE_TRANSITIONS: Dict[StartCondition, Dict[int, List[Tuple[int, int, int]]]] = {\n",
    );
    for (cond, dfa) in dfas {
        code.push_str(&format!("    StartCondition.{}: {{\n", cond));
        for state in &dfa.states {
            if !state.range_transitions.is_empty() {
                code.push_str(&format!("        {}: [", state.id));
                for &(start_cp, end_cp, target) in &state.range_transitions {
                    code.push_str(&format!("(0x{:X}, 0x{:X}, {}), ", start_cp, end_cp, target));
                }
                code.push_str("],\n");
            } else if !state.transitions.is_empty() {
                // Fallback to char-based as ranges
                code.push_str(&format!("        {}: [", state.id));
                for (ch, target) in &state.transitions {
                    let cp = *ch as u32;
                    code.push_str(&format!("(0x{:X}, 0x{:X}, {}), ", cp, cp, target));
                }
                code.push_str("],\n");
            }
        }
        code.push_str("    },\n");
    }
    code.push_str("}\n\n");

    // Accepting states per condition
    code.push_str("# Accepting states: condition -> {state_id: rule_index}\n");
    code.push_str("ACCEPTING: Dict[StartCondition, Dict[int, int]] = {\n");
    for (cond, dfa) in dfas {
        code.push_str(&format!("    StartCondition.{}: {{\n", cond));
        for state in &dfa.states {
            if state.is_accepting {
                if let Some(rule_idx) = state.rule_index {
                    code.push_str(&format!("        {}: {},\n", state.id, rule_idx));
                }
            }
        }
        code.push_str("    },\n");
    }
    code.push_str("}\n\n");

    // Lexer class with start condition support
    code.push_str("class Lexer:\n");
    code.push_str("    def __init__(self, input_str: str):\n");
    code.push_str("        self.input = input_str\n");
    code.push_str("        self.pos = 0\n");
    code.push_str("        self.line = 1\n");
    code.push_str("        self.column = 1\n");
    code.push_str("        self.condition = StartCondition.INITIAL\n");
    code.push_str("        self._condition_stack: list = []\n\n");

    code.push_str("    def begin(self, condition: StartCondition):\n");
    code.push_str("        \"\"\"Switch to a new start condition.\"\"\"\n");
    code.push_str("        self.condition = condition\n\n");

    code.push_str("    def push_state(self, condition: StartCondition):\n");
    code.push_str("        \"\"\"Push current condition and switch to new one.\"\"\"\n");
    code.push_str("        self._condition_stack.append(self.condition)\n");
    code.push_str("        self.condition = condition\n\n");

    code.push_str("    def pop_state(self):\n");
    code.push_str("        \"\"\"Pop and restore previous condition.\"\"\"\n");
    code.push_str("        if self._condition_stack:\n");
    code.push_str("            self.condition = self._condition_stack.pop()\n\n");

    code.push_str("    def _get_next_state(self, state: int, codepoint: int) -> int:\n");
    code.push_str("        \"\"\"Find next state using range-based transitions.\"\"\"\n");
    code.push_str("        trans_table = RANGE_TRANSITIONS.get(self.condition, {})\n");
    code.push_str("        ranges = trans_table.get(state, [])\n");
    code.push_str("        for start_cp, end_cp, target in ranges:\n");
    code.push_str("            if start_cp <= codepoint <= end_cp:\n");
    code.push_str("                return target\n");
    code.push_str("        return -1\n\n");

    code.push_str("    def next_token(self) -> Token:\n");
    code.push_str("        while self.pos < len(self.input):\n");
    code.push_str("            start = self.pos\n");
    code.push_str("            start_line = self.line\n");
    code.push_str("            start_column = self.column\n");
    code.push_str("            state = 0\n");
    code.push_str("            last_accepting_rule = -1\n");
    code.push_str("            last_accepting_pos = start\n\n");

    code.push_str("            accept_table = ACCEPTING.get(self.condition, {})\n\n");

    code.push_str("            while self.pos < len(self.input):\n");
    code.push_str("                c = self.input[self.pos]\n");
    code.push_str("                codepoint = ord(c)\n");
    code.push_str("                next_state = self._get_next_state(state, codepoint)\n");
    code.push_str("                if next_state == -1:\n");
    code.push_str("                    break\n");
    code.push_str("                state = next_state\n");
    code.push_str("                self.pos += 1\n");
    code.push_str("                # Track line/column\n");
    code.push_str("                if c == '\\n':\n");
    code.push_str("                    self.line += 1\n");
    code.push_str("                    self.column = 1\n");
    code.push_str("                else:\n");
    code.push_str("                    self.column += 1\n\n");

    code.push_str("                if state in accept_table:\n");
    code.push_str("                    last_accepting_rule = accept_table[state]\n");
    code.push_str("                    last_accepting_pos = self.pos\n\n");

    code.push_str("            if last_accepting_rule >= 0:\n");
    code.push_str("                self.pos = last_accepting_pos\n");
    code.push_str(
        "                action = RULE_ACTIONS.get(last_accepting_rule, (TokenType.ERROR, None))\n",
    );
    code.push_str("                token_type, new_condition = action\n");
    code.push_str("                text = self.input[start:last_accepting_pos]\n\n");
    code.push_str("                # Handle state change\n");
    code.push_str("                if new_condition is not None:\n");
    code.push_str("                    self.condition = new_condition\n\n");
    code.push_str("                if token_type is None:  # Skip\n");
    code.push_str("                    continue\n");
    code.push_str(
        "                return Token(token_type, text, start, start_line, start_column)\n",
    );
    code.push_str("            else:\n");
    code.push_str("                # No match - return error token for single char\n");
    code.push_str("                self.pos = start + 1\n");
    code.push_str("                if self.input[start] == '\\n':\n");
    code.push_str("                    self.line += 1\n");
    code.push_str("                    self.column = 1\n");
    code.push_str("                else:\n");
    code.push_str("                    self.column += 1\n");
    code.push_str("                return Token(TokenType.ERROR, self.input[start:self.pos], start, start_line, start_column)\n\n");

    code.push_str("        return Token(TokenType.EOF, '', self.pos, self.line, self.column)\n\n");

    code.push_str("    def tokenize(self):\n");
    code.push_str("        \"\"\"Generator that yields all tokens.\"\"\"\n");
    code.push_str("        while True:\n");
    code.push_str("            token = self.next_token()\n");
    code.push_str("            yield token\n");
    code.push_str("            if token.type == TokenType.EOF:\n");
    code.push_str("                break\n");

    // Built-in test driver
    code.push_str("\n\n");
    code.push_str(&generate_python_test_driver());

    Ok(code)
}

fn generate_c_with_conditions(dfas: &HashMap<String, Dfa>, spec: &LexerSpec) -> Result<String> {
    let mut code = String::new();

    code.push_str("/**\n");
    code.push_str(" * Lexer generated by OpenLexer with start condition support.\n");
    code.push_str(" */\n\n");
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("#include <stdint.h>\n\n");

    // UTF-8 decode function for Unicode support
    code.push_str("/* UTF-8 decoding: read a codepoint from UTF-8 string */\n");
    code.push_str("static uint32_t utf8_decode(const char** ptr) {\n");
    code.push_str("    const unsigned char* s = (const unsigned char*)*ptr;\n");
    code.push_str("    uint32_t cp;\n");
    code.push_str("    int len;\n");
    code.push_str("    if (*s == 0) return 0;\n");
    code.push_str("    if (*s < 0x80) { cp = *s; len = 1; }\n");
    code.push_str("    else if ((*s & 0xE0) == 0xC0) { cp = *s & 0x1F; len = 2; }\n");
    code.push_str("    else if ((*s & 0xF0) == 0xE0) { cp = *s & 0x0F; len = 3; }\n");
    code.push_str("    else if ((*s & 0xF8) == 0xF0) { cp = *s & 0x07; len = 4; }\n");
    code.push_str("    else { *ptr = (const char*)(s + 1); return 0xFFFD; } /* invalid */\n");
    code.push_str("    for (int i = 1; i < len; i++) {\n");
    code.push_str(
        "        if ((s[i] & 0xC0) != 0x80) { *ptr = (const char*)(s + 1); return 0xFFFD; }\n",
    );
    code.push_str("        cp = (cp << 6) | (s[i] & 0x3F);\n");
    code.push_str("    }\n");
    code.push_str("    *ptr = (const char*)(s + len);\n");
    code.push_str("    return cp;\n");
    code.push_str("}\n\n");

    code.push_str("/* Get byte length of UTF-8 character */\n");
    code.push_str("static int utf8_char_len(const char* s) {\n");
    code.push_str("    unsigned char c = (unsigned char)*s;\n");
    code.push_str("    if (c == 0) return 0;\n");
    code.push_str("    if (c < 0x80) return 1;\n");
    code.push_str("    if ((c & 0xE0) == 0xC0) return 2;\n");
    code.push_str("    if ((c & 0xF0) == 0xE0) return 3;\n");
    code.push_str("    if ((c & 0xF8) == 0xF0) return 4;\n");
    code.push_str("    return 1; /* invalid, skip one byte */\n");
    code.push_str("}\n\n");

    // Token type enum
    code.push_str("typedef enum {\n");
    code.push_str("    TOKEN_EOF,\n");
    code.push_str("    TOKEN_ERROR,\n");
    let mut seen_tokens = std::collections::HashSet::new();
    seen_tokens.insert("EOF".to_string());
    seen_tokens.insert("ERROR".to_string());
    for rule in &spec.rules {
        match &rule.action {
            RuleAction::Token(name) | RuleAction::TokenAndBegin(name, _) => {
                let upper = name.to_uppercase();
                if seen_tokens.insert(upper.clone()) {
                    code.push_str(&format!("    TOKEN_{},\n", upper));
                }
            }
            _ => {}
        }
    }
    code.push_str("} TokenType;\n\n");

    // Start condition enum
    code.push_str("typedef enum {\n");
    for (idx, cond) in spec.start_conditions.keys().enumerate() {
        code.push_str(&format!("    CONDITION_{} = {},\n", cond, idx));
    }
    code.push_str("} StartCondition;\n\n");

    // Token struct
    code.push_str("typedef struct {\n");
    code.push_str("    TokenType type;\n");
    code.push_str("    const char* start;\n");
    code.push_str("    int length;\n");
    code.push_str("    int line;\n");
    code.push_str("    int column;\n");
    code.push_str("} Token;\n\n");

    // Lexer struct
    code.push_str("typedef struct {\n");
    code.push_str("    const char* input;\n");
    code.push_str("    const char* current;\n");
    code.push_str("    int line;\n");
    code.push_str("    int column;\n");
    code.push_str("    StartCondition condition;\n");
    code.push_str("    StartCondition condition_stack[32];\n");
    code.push_str("    int condition_stack_size;\n");
    code.push_str("    /* yymore support */\n");
    code.push_str("    int yymore_flag;\n");
    code.push_str("    const char* yymore_start;\n");
    code.push_str("    /* REJECT support - stores backup of matches */\n");
    code.push_str("    int reject_active;\n");
    code.push_str("    int reject_rule_index;\n");
    code.push_str("    struct {\n");
    code.push_str("        int rule;\n");
    code.push_str("        const char* pos;\n");
    code.push_str("        int line;\n");
    code.push_str("        int column;\n");
    code.push_str("    } reject_stack[64];\n");
    code.push_str("    int reject_stack_size;\n");
    code.push_str("} Lexer;\n\n");

    // Global yytext and yyleng variables (set during lexing)
    code.push_str("/* Global lex variables */\n");
    code.push_str("static const char* yytext = NULL;\n");
    code.push_str("static int yyleng = 0;\n");
    code.push_str("static int yylineno = 1;\n");
    code.push_str("static Lexer* yylex_lexer = NULL;\n\n");

    // yymore macro
    code.push_str("/* yymore() - append next match to current yytext */\n");
    code.push_str(
        "#define yymore() do { if (yylex_lexer) yylex_lexer->yymore_flag = 1; } while(0)\n\n",
    );

    // yyless macro
    code.push_str("/* yyless(n) - return all but first n characters to input */\n");
    code.push_str("#define yyless(n) do { \\\n");
    code.push_str("    if (yylex_lexer && (n) >= 0 && (n) <= yyleng) { \\\n");
    code.push_str("        int put_back = yyleng - (n); \\\n");
    code.push_str("        yylex_lexer->current -= put_back; \\\n");
    code.push_str("        yyleng = (n); \\\n");
    code.push_str("    } \\\n");
    code.push_str("} while(0)\n\n");

    // REJECT macro
    code.push_str("/* REJECT - try the next matching rule */\n");
    code.push_str("#define REJECT do { \\\n");
    code.push_str("    if (yylex_lexer && yylex_lexer->reject_stack_size > 0) { \\\n");
    code.push_str("        yylex_lexer->reject_active = 1; \\\n");
    code.push_str("    } \\\n");
    code.push_str("} while(0)\n\n");

    // input() function
    code.push_str("/* input() - read next character from input */\n");
    code.push_str("static int input(void) {\n");
    code.push_str("    if (yylex_lexer && *yylex_lexer->current != '\\0') {\n");
    code.push_str("        char c = *yylex_lexer->current++;\n");
    code.push_str("        if (c == '\\n') {\n");
    code.push_str("            yylex_lexer->line++;\n");
    code.push_str("            yylex_lexer->column = 1;\n");
    code.push_str("        } else {\n");
    code.push_str("            yylex_lexer->column++;\n");
    code.push_str("        }\n");
    code.push_str("        return (unsigned char)c;\n");
    code.push_str("    }\n");
    code.push_str("    return EOF;\n");
    code.push_str("}\n\n");

    // unput() function
    code.push_str("/* unput(c) - push character back to input */\n");
    code.push_str("static void unput(int c) {\n");
    code.push_str("    if (yylex_lexer && yylex_lexer->current > yylex_lexer->input) {\n");
    code.push_str("        yylex_lexer->current--;\n");
    code.push_str("        if (c == '\\n') {\n");
    code.push_str("            yylex_lexer->line--;\n");
    code.push_str("            /* column tracking for unput is approximate */\n");
    code.push_str("        } else {\n");
    code.push_str("            yylex_lexer->column--;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Init function
    code.push_str("void lexer_init(Lexer* lexer, const char* input) {\n");
    code.push_str("    lexer->input = input;\n");
    code.push_str("    lexer->current = input;\n");
    code.push_str("    lexer->line = 1;\n");
    code.push_str("    lexer->column = 1;\n");
    code.push_str("    lexer->condition = CONDITION_INITIAL;\n");
    code.push_str("    lexer->condition_stack_size = 0;\n");
    code.push_str("    lexer->yymore_flag = 0;\n");
    code.push_str("    lexer->yymore_start = input;\n");
    code.push_str("    lexer->reject_active = 0;\n");
    code.push_str("    lexer->reject_stack_size = 0;\n");
    code.push_str("    yylex_lexer = lexer;\n");
    code.push_str("}\n\n");

    // Begin function
    code.push_str("void lexer_begin(Lexer* lexer, StartCondition condition) {\n");
    code.push_str("    lexer->condition = condition;\n");
    code.push_str("}\n\n");

    // Push/pop state functions
    code.push_str("void lexer_push_state(Lexer* lexer, StartCondition condition) {\n");
    code.push_str("    if (lexer->condition_stack_size < 32) {\n");
    code.push_str(
        "        lexer->condition_stack[lexer->condition_stack_size++] = lexer->condition;\n",
    );
    code.push_str("    }\n");
    code.push_str("    lexer->condition = condition;\n");
    code.push_str("}\n\n");

    code.push_str("void lexer_pop_state(Lexer* lexer) {\n");
    code.push_str("    if (lexer->condition_stack_size > 0) {\n");
    code.push_str(
        "        lexer->condition = lexer->condition_stack[--lexer->condition_stack_size];\n",
    );
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate transition function for each condition using range-based transitions
    for (cond, dfa) in dfas {
        code.push_str(&format!(
            "static int transition_{cond}(int state, uint32_t cp) {{\n"
        ));
        code.push_str("    switch (state) {\n");
        for state in &dfa.states {
            code.push_str(&format!("        case {}:\n", state.id));

            // Use range_transitions if available, fall back to char transitions
            if !state.range_transitions.is_empty() {
                for &(start_cp, end_cp, target) in &state.range_transitions {
                    if start_cp == end_cp {
                        code.push_str(&format!(
                            "            if (cp == 0x{:X}) return {};\n",
                            start_cp, target
                        ));
                    } else {
                        code.push_str(&format!(
                            "            if (cp >= 0x{:X} && cp <= 0x{:X}) return {};\n",
                            start_cp, end_cp, target
                        ));
                    }
                }
                code.push_str("            return -1;\n");
            } else if !state.transitions.is_empty() {
                // Fallback to legacy char-based switch
                code.push_str("            switch (cp) {\n");
                for (ch, target) in &state.transitions {
                    let ch_repr = escape_c_char(*ch);
                    code.push_str(&format!(
                        "                case {}: return {};\n",
                        ch_repr, target
                    ));
                }
                code.push_str("                default: return -1;\n");
                code.push_str("            }\n");
            } else {
                code.push_str("            return -1;\n");
            }
        }
        code.push_str("        default: return -1;\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");
    }

    // Generate accepting state function for each condition
    for (cond, dfa) in dfas {
        code.push_str(&format!("static int accepting_{cond}(int state) {{\n"));
        code.push_str("    switch (state) {\n");
        for state in &dfa.states {
            if state.is_accepting {
                if let Some(rule_idx) = state.rule_index {
                    code.push_str(&format!(
                        "        case {}: return {};\n",
                        state.id, rule_idx
                    ));
                }
            }
        }
        code.push_str("        default: return -1;\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");
    }

    // Generate dispatch transition function
    code.push_str("static int transition(StartCondition cond, int state, uint32_t cp) {\n");
    code.push_str("    switch (cond) {\n");
    for cond in dfas.keys() {
        code.push_str(&format!(
            "        case CONDITION_{}: return transition_{}(state, cp);\n",
            cond, cond
        ));
    }
    code.push_str("        default: return -1;\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate dispatch accepting function
    code.push_str("static int accepting(StartCondition cond, int state) {\n");
    code.push_str("    switch (cond) {\n");
    for cond in dfas.keys() {
        code.push_str(&format!(
            "        case CONDITION_{}: return accepting_{}(state);\n",
            cond, cond
        ));
    }
    code.push_str("        default: return -1;\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Rule action function - returns (token_type, new_condition or -1)
    code.push_str("typedef struct { TokenType token; int new_condition; } RuleAction;\n\n");
    code.push_str("static RuleAction get_rule_action(int rule_index) {\n");
    code.push_str("    switch (rule_index) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        let (token_str, cond_str) = match &rule.action {
            RuleAction::Token(name) => (format!("TOKEN_{}", name.to_uppercase()), "-1".to_string()),
            RuleAction::TokenAndBegin(name, state) => (
                format!("TOKEN_{}", name.to_uppercase()),
                format!("CONDITION_{}", state),
            ),
            RuleAction::Skip => {
                ("TOKEN_EOF".to_string(), "-1".to_string()) // TOKEN_EOF with -1 means skip
            }
            RuleAction::Begin(state) => ("TOKEN_EOF".to_string(), format!("CONDITION_{}", state)),
            RuleAction::Error => ("TOKEN_ERROR".to_string(), "-1".to_string()),
            RuleAction::Code(_) => {
                // Code rules return special marker - handled by inline action code
                ("TOKEN_EOF".to_string(), "-2".to_string())
            }
        };
        code.push_str(&format!(
            "        case {}: return (RuleAction){{ {}, {} }};\n",
            idx, token_str, cond_str
        ));
    }
    code.push_str("        default: return (RuleAction){ TOKEN_ERROR, -1 };\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Is-skip helper
    code.push_str("static int is_skip_rule(int rule_index) {\n");
    code.push_str("    switch (rule_index) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        if matches!(&rule.action, RuleAction::Skip | RuleAction::Begin(_)) {
            code.push_str(&format!("        case {}: return 1;\n", idx));
        }
    }
    code.push_str("        default: return 0;\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Main next_token function
    code.push_str("Token lexer_next(Lexer* lexer) {\n");
    code.push_str("    Token token;\n");
    code.push_str("    token.type = TOKEN_EOF;\n");
    code.push_str("    token.start = lexer->current;\n");
    code.push_str("    token.length = 0;\n");
    code.push_str("    token.line = lexer->line;\n");
    code.push_str("    token.column = lexer->column;\n\n");

    code.push_str(
        "    /* Handle yymore: if flag is set, start from yymore_start instead of current */\n",
    );
    code.push_str("    const char* yymore_preserved_start = lexer->yymore_start;\n\n");

    code.push_str("    while (*lexer->current != '\\0') {\n");
    code.push_str("        const char* start;\n");
    code.push_str("        if (lexer->yymore_flag) {\n");
    code.push_str("            start = yymore_preserved_start;\n");
    code.push_str("            lexer->yymore_flag = 0;\n");
    code.push_str("        } else {\n");
    code.push_str("            start = lexer->current;\n");
    code.push_str("            lexer->yymore_start = start;\n");
    code.push_str("        }\n");
    code.push_str("        int start_line = lexer->line;\n");
    code.push_str("        int start_column = lexer->column;\n");
    code.push_str("        int state = 0;\n");
    code.push_str("        int last_accepting_rule = -1;\n");
    code.push_str("        const char* last_accepting_pos = lexer->current;\n");
    code.push_str("        int last_accepting_line = lexer->line;\n");
    code.push_str("        int last_accepting_column = lexer->column;\n\n");

    code.push_str("        /* Clear reject stack for this match attempt */\n");
    code.push_str("        lexer->reject_stack_size = 0;\n");
    code.push_str("        lexer->reject_active = 0;\n\n");

    code.push_str("        while (*lexer->current != '\\0') {\n");
    code.push_str("            const char* before = lexer->current;\n");
    code.push_str("            uint32_t cp = utf8_decode(&lexer->current);\n");
    code.push_str("            if (cp == 0) break;\n");
    code.push_str("            int next_state = transition(lexer->condition, state, cp);\n");
    code.push_str("            if (next_state < 0) { lexer->current = before; break; }\n");
    code.push_str("            state = next_state;\n");
    code.push_str("            if (cp == '\\n') {\n");
    code.push_str("                lexer->line++;\n");
    code.push_str("                lexer->column = 1;\n");
    code.push_str("            } else {\n");
    code.push_str("                lexer->column++;\n");
    code.push_str("            }\n");
    code.push_str("            int rule = accepting(lexer->condition, state);\n");
    code.push_str("            if (rule >= 0) {\n");
    code.push_str("                /* Store in reject stack for potential REJECT */\n");
    code.push_str("                if (lexer->reject_stack_size < 64) {\n");
    code.push_str(
        "                    lexer->reject_stack[lexer->reject_stack_size].rule = rule;\n",
    );
    code.push_str(
        "                    lexer->reject_stack[lexer->reject_stack_size].pos = lexer->current;\n",
    );
    code.push_str(
        "                    lexer->reject_stack[lexer->reject_stack_size].line = lexer->line;\n",
    );
    code.push_str("                    lexer->reject_stack[lexer->reject_stack_size].column = lexer->column;\n");
    code.push_str("                    lexer->reject_stack_size++;\n");
    code.push_str("                }\n");
    code.push_str("                last_accepting_rule = rule;\n");
    code.push_str("                last_accepting_pos = lexer->current;\n");
    code.push_str("                last_accepting_line = lexer->line;\n");
    code.push_str("                last_accepting_column = lexer->column;\n");
    code.push_str("            }\n");
    code.push_str("        }\n\n");

    code.push_str("try_rule:\n");
    code.push_str("        if (last_accepting_rule >= 0) {\n");
    code.push_str("            lexer->current = last_accepting_pos;\n");
    code.push_str("            lexer->line = last_accepting_line;\n");
    code.push_str("            lexer->column = last_accepting_column;\n\n");
    code.push_str("            /* Set global yytext and yyleng */\n");
    code.push_str("            yytext = (char*)start;\n");
    code.push_str("            yyleng = (int)(last_accepting_pos - start);\n");
    code.push_str("            yylineno = start_line;\n\n");
    code.push_str("            RuleAction action = get_rule_action(last_accepting_rule);\n");
    code.push_str("            if (action.new_condition >= 0) {\n");
    code.push_str("                lexer->condition = (StartCondition)action.new_condition;\n");
    code.push_str("            }\n\n");
    code.push_str("            /* Check for REJECT after potential user code execution */\n");
    code.push_str("            if (lexer->reject_active) {\n");
    code.push_str("                lexer->reject_active = 0;\n");
    code.push_str("                /* Try next match from reject stack */\n");
    code.push_str("                if (lexer->reject_stack_size > 1) {\n");
    code.push_str("                    lexer->reject_stack_size--;\n");
    code.push_str("                    int idx = lexer->reject_stack_size - 1;\n");
    code.push_str("                    last_accepting_rule = lexer->reject_stack[idx].rule;\n");
    code.push_str("                    last_accepting_pos = lexer->reject_stack[idx].pos;\n");
    code.push_str("                    last_accepting_line = lexer->reject_stack[idx].line;\n");
    code.push_str("                    last_accepting_column = lexer->reject_stack[idx].column;\n");
    code.push_str("                    goto try_rule;\n");
    code.push_str("                }\n");
    code.push_str("            }\n\n");
    code.push_str("            if (is_skip_rule(last_accepting_rule)) {\n");
    code.push_str("                continue;\n");
    code.push_str("            }\n");
    code.push_str("            token.type = action.token;\n");
    code.push_str("            token.start = start;\n");
    code.push_str("            token.length = (int)(last_accepting_pos - start);\n");
    code.push_str("            token.line = start_line;\n");
    code.push_str("            token.column = start_column;\n");
    code.push_str("            return token;\n");
    code.push_str("        } else {\n");
    code.push_str("            /* No match - error token for one UTF-8 character */\n");
    code.push_str("            int char_len = utf8_char_len(start);\n");
    code.push_str("            if (char_len == 0) char_len = 1;\n");
    code.push_str("            lexer->current = start + char_len;\n");
    code.push_str("            if (*start == '\\n') {\n");
    code.push_str("                lexer->line++;\n");
    code.push_str("                lexer->column = 1;\n");
    code.push_str("            } else {\n");
    code.push_str("                lexer->column++;\n");
    code.push_str("            }\n");
    code.push_str("            yytext = (char*)start;\n");
    code.push_str("            yyleng = char_len;\n");
    code.push_str("            token.type = TOKEN_ERROR;\n");
    code.push_str("            token.start = start;\n");
    code.push_str("            token.length = char_len;\n");
    code.push_str("            token.line = start_line;\n");
    code.push_str("            token.column = start_column;\n");
    code.push_str("            return token;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    yytext = (char*)lexer->current;\n");
    code.push_str("    yyleng = 0;\n");
    code.push_str("    token.type = TOKEN_EOF;\n");
    code.push_str("    token.start = lexer->current;\n");
    code.push_str("    token.length = 0;\n");
    code.push_str("    token.line = lexer->line;\n");
    code.push_str("    token.column = lexer->column;\n");
    code.push_str("    return token;\n");
    code.push_str("}\n");

    // Built-in test driver
    code.push_str("\n");
    code.push_str(&generate_c_test_driver());

    Ok(code)
}

fn generate_java_with_conditions(dfas: &HashMap<String, Dfa>, spec: &LexerSpec) -> Result<String> {
    let mut code = String::new();

    code.push_str("/**\n");
    code.push_str(" * Lexer generated by OpenLexer with start condition support.\n");
    code.push_str(" */\n\n");
    code.push_str("import java.util.ArrayList;\n");
    code.push_str("import java.util.List;\n\n");

    // Token type enum
    code.push_str("enum TokenType {\n");
    code.push_str("    EOF,\n");
    code.push_str("    ERROR,\n");
    let mut seen_tokens = std::collections::HashSet::new();
    seen_tokens.insert("EOF".to_string());
    seen_tokens.insert("ERROR".to_string());
    for rule in &spec.rules {
        match &rule.action {
            RuleAction::Token(name) | RuleAction::TokenAndBegin(name, _) => {
                let upper = name.to_uppercase();
                if seen_tokens.insert(upper.clone()) {
                    code.push_str(&format!("    {},\n", upper));
                }
            }
            _ => {}
        }
    }
    code.push_str("}\n\n");

    // Start condition enum
    code.push_str("enum StartCondition {\n");
    for (idx, cond) in spec.start_conditions.keys().enumerate() {
        if idx > 0 {
            code.push_str(",\n");
        }
        code.push_str(&format!("    {}", cond));
    }
    code.push_str("\n}\n\n");

    // Token class
    code.push_str("class Token {\n");
    code.push_str("    public final TokenType type;\n");
    code.push_str("    public final String text;\n");
    code.push_str("    public final int pos;\n");
    code.push_str("    public final int line;\n");
    code.push_str("    public final int column;\n\n");
    code.push_str(
        "    public Token(TokenType type, String text, int pos, int line, int column) {\n",
    );
    code.push_str("        this.type = type;\n");
    code.push_str("        this.text = text;\n");
    code.push_str("        this.pos = pos;\n");
    code.push_str("        this.line = line;\n");
    code.push_str("        this.column = column;\n");
    code.push_str("    }\n\n");
    code.push_str("    @Override\n");
    code.push_str("    public String toString() {\n");
    code.push_str(
        "        return String.format(\"Token(%s, \\\"%s\\\", pos=%d, line=%d, col=%d)\",\n",
    );
    code.push_str("                type, text.replace(\"\\n\", \"\\\\n\"), pos, line, column);\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Lexer class
    code.push_str("public class Lexer {\n");
    code.push_str("    private final String input;\n");
    code.push_str("    private int pos = 0;\n");
    code.push_str("    private int line = 1;\n");
    code.push_str("    private int column = 1;\n");
    code.push_str("    private StartCondition condition = StartCondition.INITIAL;\n");
    code.push_str("    private final List<StartCondition> conditionStack = new ArrayList<>();\n\n");

    code.push_str("    public Lexer(String input) {\n");
    code.push_str("        this.input = input;\n");
    code.push_str("    }\n\n");

    code.push_str("    public void begin(StartCondition condition) {\n");
    code.push_str("        this.condition = condition;\n");
    code.push_str("    }\n\n");

    code.push_str("    public void pushState(StartCondition condition) {\n");
    code.push_str("        conditionStack.add(this.condition);\n");
    code.push_str("        this.condition = condition;\n");
    code.push_str("    }\n\n");

    code.push_str("    public void popState() {\n");
    code.push_str("        if (!conditionStack.isEmpty()) {\n");
    code.push_str(
        "            this.condition = conditionStack.remove(conditionStack.size() - 1);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Generate transition method
    code.push_str("    private int transition(int state, char c) {\n");
    code.push_str("        switch (condition) {\n");
    for cond in dfas.keys() {
        code.push_str(&format!(
            "            case {}: return transition_{}(state, c);\n",
            cond, cond
        ));
    }
    code.push_str("            default: return -1;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Generate per-condition transition methods
    for (cond, dfa) in dfas {
        code.push_str(&format!(
            "    private int transition_{}(int state, char c) {{\n",
            cond
        ));
        code.push_str("        switch (state) {\n");
        for state in &dfa.states {
            code.push_str(&format!("            case {}:\n", state.id));
            code.push_str("                switch (c) {\n");
            for (ch, target) in &state.transitions {
                let ch_repr = escape_java_char(*ch);
                code.push_str(&format!(
                    "                    case {}: return {};\n",
                    ch_repr, target
                ));
            }
            code.push_str("                    default: return -1;\n");
            code.push_str("                }\n");
        }
        code.push_str("            default: return -1;\n");
        code.push_str("        }\n");
        code.push_str("    }\n\n");
    }

    // Generate accepting method
    code.push_str("    private int accepting(int state) {\n");
    code.push_str("        switch (condition) {\n");
    for cond in dfas.keys() {
        code.push_str(&format!(
            "            case {}: return accepting_{}(state);\n",
            cond, cond
        ));
    }
    code.push_str("            default: return -1;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Generate per-condition accepting methods
    for (cond, dfa) in dfas {
        code.push_str(&format!(
            "    private int accepting_{}(int state) {{\n",
            cond
        ));
        code.push_str("        switch (state) {\n");
        for state in &dfa.states {
            if state.is_accepting {
                if let Some(rule_idx) = state.rule_index {
                    code.push_str(&format!(
                        "            case {}: return {};\n",
                        state.id, rule_idx
                    ));
                }
            }
        }
        code.push_str("            default: return -1;\n");
        code.push_str("        }\n");
        code.push_str("    }\n\n");
    }

    // Get token type from rule index
    code.push_str("    private TokenType getTokenType(int ruleIndex) {\n");
    code.push_str("        switch (ruleIndex) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        let token_str = match &rule.action {
            RuleAction::Token(name) | RuleAction::TokenAndBegin(name, _) => {
                format!("TokenType.{}", name.to_uppercase())
            }
            RuleAction::Skip | RuleAction::Begin(_) => "null".to_string(),
            RuleAction::Error => "TokenType.ERROR".to_string(),
            RuleAction::Code(_) => "null".to_string(), // Code actions handled separately
        };
        code.push_str(&format!(
            "            case {}: return {};\n",
            idx, token_str
        ));
    }
    code.push_str("            default: return TokenType.ERROR;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Handle state change from rule
    code.push_str("    private void handleStateChange(int ruleIndex) {\n");
    code.push_str("        switch (ruleIndex) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        match &rule.action {
            RuleAction::TokenAndBegin(_, state) | RuleAction::Begin(state) => {
                code.push_str(&format!(
                    "            case {}: condition = StartCondition.{}; break;\n",
                    idx, state
                ));
            }
            _ => {}
        }
    }
    code.push_str("            default: break;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Check if rule is skip
    code.push_str("    private boolean isSkipRule(int ruleIndex) {\n");
    code.push_str("        switch (ruleIndex) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        if matches!(&rule.action, RuleAction::Skip | RuleAction::Begin(_)) {
            code.push_str(&format!("            case {}: return true;\n", idx));
        }
    }
    code.push_str("            default: return false;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // nextToken method
    code.push_str("    public Token nextToken() {\n");
    code.push_str("        while (pos < input.length()) {\n");
    code.push_str("            int start = pos;\n");
    code.push_str("            int startLine = line;\n");
    code.push_str("            int startColumn = column;\n");
    code.push_str("            int state = 0;\n");
    code.push_str("            int lastAcceptingRule = -1;\n");
    code.push_str("            int lastAcceptingPos = start;\n\n");

    code.push_str("            while (pos < input.length()) {\n");
    code.push_str("                char c = input.charAt(pos);\n");
    code.push_str("                int nextState = transition(state, c);\n");
    code.push_str("                if (nextState < 0) break;\n");
    code.push_str("                state = nextState;\n");
    code.push_str("                pos++;\n");
    code.push_str("                if (c == '\\n') {\n");
    code.push_str("                    line++;\n");
    code.push_str("                    column = 1;\n");
    code.push_str("                } else {\n");
    code.push_str("                    column++;\n");
    code.push_str("                }\n");
    code.push_str("                int rule = accepting(state);\n");
    code.push_str("                if (rule >= 0) {\n");
    code.push_str("                    lastAcceptingRule = rule;\n");
    code.push_str("                    lastAcceptingPos = pos;\n");
    code.push_str("                }\n");
    code.push_str("            }\n\n");

    code.push_str("            if (lastAcceptingRule >= 0) {\n");
    code.push_str("                pos = lastAcceptingPos;\n");
    code.push_str("                handleStateChange(lastAcceptingRule);\n");
    code.push_str("                if (isSkipRule(lastAcceptingRule)) {\n");
    code.push_str("                    continue;\n");
    code.push_str("                }\n");
    code.push_str("                TokenType type = getTokenType(lastAcceptingRule);\n");
    code.push_str("                String text = input.substring(start, lastAcceptingPos);\n");
    code.push_str("                return new Token(type, text, start, startLine, startColumn);\n");
    code.push_str("            } else {\n");
    code.push_str("                pos = start + 1;\n");
    code.push_str("                if (input.charAt(start) == '\\n') {\n");
    code.push_str("                    line++;\n");
    code.push_str("                    column = 1;\n");
    code.push_str("                } else {\n");
    code.push_str("                    column++;\n");
    code.push_str("                }\n");
    code.push_str("                return new Token(TokenType.ERROR, input.substring(start, pos), start, startLine, startColumn);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        return new Token(TokenType.EOF, \"\", pos, line, column);\n");
    code.push_str("    }\n\n");

    // Tokenize method - returns list
    code.push_str("    public List<Token> tokenize() {\n");
    code.push_str("        List<Token> tokens = new ArrayList<>();\n");
    code.push_str("        while (true) {\n");
    code.push_str("            Token token = nextToken();\n");
    code.push_str("            tokens.add(token);\n");
    code.push_str("            if (token.type == TokenType.EOF) break;\n");
    code.push_str("        }\n");
    code.push_str("        return tokens;\n");
    code.push_str("    }\n");

    // Built-in test driver
    code.push_str("\n");
    code.push_str(&generate_java_test_driver());

    code.push_str("}\n");

    Ok(code)
}

// =============================================================================
// Full multi-token lexer generation (legacy - no start conditions)
// =============================================================================

fn generate_c_full(dfa: &Dfa, spec: &LexerSpec) -> Result<String> {
    let mut code = String::new();

    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("#include <stdint.h>\n\n");

    // UTF-8 decoding functions for Unicode support
    code.push_str("/* UTF-8 utility functions */\n");
    code.push_str("static int utf8_char_len(unsigned char c) {\n");
    code.push_str("    if ((c & 0x80) == 0) return 1;\n");
    code.push_str("    if ((c & 0xE0) == 0xC0) return 2;\n");
    code.push_str("    if ((c & 0xF0) == 0xE0) return 3;\n");
    code.push_str("    if ((c & 0xF8) == 0xF0) return 4;\n");
    code.push_str("    return 1;\n");
    code.push_str("}\n\n");
    code.push_str("static uint32_t utf8_decode(const char** s) {\n");
    code.push_str("    const unsigned char* p = (const unsigned char*)*s;\n");
    code.push_str("    uint32_t cp;\n");
    code.push_str("    int len = utf8_char_len(*p);\n");
    code.push_str("    switch (len) {\n");
    code.push_str("        case 1: cp = p[0]; break;\n");
    code.push_str("        case 2: cp = ((p[0] & 0x1F) << 6) | (p[1] & 0x3F); break;\n");
    code.push_str("        case 3: cp = ((p[0] & 0x0F) << 12) | ((p[1] & 0x3F) << 6) | (p[2] & 0x3F); break;\n");
    code.push_str("        case 4: cp = ((p[0] & 0x07) << 18) | ((p[1] & 0x3F) << 12) | ((p[2] & 0x3F) << 6) | (p[3] & 0x3F); break;\n");
    code.push_str("        default: cp = 0;\n");
    code.push_str("    }\n");
    code.push_str("    *s += len;\n");
    code.push_str("    return cp;\n");
    code.push_str("}\n\n");

    // Generate token type enum
    code.push_str("typedef enum {\n");
    code.push_str("    TOKEN_EOF,\n");
    code.push_str("    TOKEN_ERROR,\n");

    // Track seen tokens to avoid duplicates (EOF and ERROR are already defined)
    let mut seen_tokens = std::collections::HashSet::new();
    seen_tokens.insert("EOF".to_string());
    seen_tokens.insert("ERROR".to_string());

    for rule in &spec.rules {
        if let RuleAction::Token(name) = &rule.action {
            let upper_name = name.to_uppercase();
            if seen_tokens.insert(upper_name.clone()) {
                code.push_str(&format!("    TOKEN_{},\n", upper_name));
            }
        }
    }
    code.push_str("} TokenType;\n\n");

    // Generate token struct
    code.push_str("typedef struct {\n");
    code.push_str("    TokenType type;\n");
    code.push_str("    const char* start;\n");
    code.push_str("    int length;\n");
    code.push_str("} Token;\n\n");

    // Generate lexer state
    code.push_str("typedef struct {\n");
    code.push_str("    const char* input;\n");
    code.push_str("    const char* current;\n");
    code.push_str("} Lexer;\n\n");

    // Generate init function
    code.push_str("void lexer_init(Lexer* lexer, const char* input) {\n");
    code.push_str("    lexer->input = input;\n");
    code.push_str("    lexer->current = input;\n");
    code.push_str("}\n\n");

    // Generate rule index to token mapping
    code.push_str("static TokenType rule_to_token(int rule_index) {\n");
    code.push_str("    switch (rule_index) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        match &rule.action {
            RuleAction::Token(name) => {
                code.push_str(&format!(
                    "        case {}: return TOKEN_{};\n",
                    idx,
                    name.to_uppercase()
                ));
            }
            RuleAction::TokenAndBegin(name, _) => {
                code.push_str(&format!(
                    "        case {}: return TOKEN_{};\n",
                    idx,
                    name.to_uppercase()
                ));
            }
            RuleAction::Skip | RuleAction::Begin(_) => {
                code.push_str(&format!(
                    "        case {}: return TOKEN_EOF; // Skip or state change\n",
                    idx
                ));
            }
            RuleAction::Error => {
                code.push_str(&format!("        case {}: return TOKEN_ERROR;\n", idx));
            }
            RuleAction::Code(_) => {
                code.push_str(&format!(
                    "        case {}: return TOKEN_EOF; // Code action handled separately\n",
                    idx
                ));
            }
        }
    }
    code.push_str("        default: return TOKEN_ERROR;\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate next_token function
    code.push_str("Token lexer_next(Lexer* lexer) {\n");
    code.push_str("    Token token;\n");
    code.push_str("    token.type = TOKEN_EOF;\n");
    code.push_str("    token.start = lexer->current;\n");
    code.push_str("    token.length = 0;\n\n");

    code.push_str("    while (*lexer->current != '\\0') {\n");
    code.push_str("        const char* start = lexer->current;\n");
    code.push_str("        int state = 0;\n");
    code.push_str("        int last_accepting_state = -1;\n");
    code.push_str("        int last_accepting_rule = -1;\n");
    code.push_str("        const char* last_accepting_pos = start;\n\n");

    // Main DFA loop - now uses range-based transitions for Unicode support
    code.push_str("        while (*lexer->current != '\\0') {\n");
    code.push_str("            int next_state = -1;\n");
    code.push_str("            const char* before = lexer->current;\n");
    code.push_str("            uint32_t cp = utf8_decode(&lexer->current);\n");
    code.push_str("            if (cp == 0) break;\n");
    code.push_str("            switch (state) {\n");

    for state in &dfa.states {
        code.push_str(&format!("                case {}:\n", state.id));
        // Use range-based transitions if available
        if !state.range_transitions.is_empty() {
            let mut first = true;
            for &(start_cp, end_cp, target) in &state.range_transitions {
                let prefix = if first { "if" } else { "else if" };
                first = false;
                if start_cp == end_cp {
                    code.push_str(&format!(
                        "                    {} (cp == 0x{:X}) next_state = {};\n",
                        prefix, start_cp, target
                    ));
                } else {
                    code.push_str(&format!(
                        "                    {} (cp >= 0x{:X} && cp <= 0x{:X}) next_state = {};\n",
                        prefix, start_cp, end_cp, target
                    ));
                }
            }
            code.push_str("                    /* else next_state stays -1 */\n");
        } else if !state.transitions.is_empty() {
            // Fallback to char-based for legacy DFAs
            let mut first = true;
            for (ch, target) in &state.transitions {
                let prefix = if first { "if" } else { "else if" };
                first = false;
                let cp_val = *ch as u32;
                code.push_str(&format!(
                    "                    {} (cp == 0x{:X}) next_state = {};\n",
                    prefix, cp_val, target
                ));
            }
            code.push_str("                    /* else next_state stays -1 */\n");
        } else {
            code.push_str("                    next_state = -1;\n");
        }
        code.push_str("                    break;\n");
    }

    code.push_str("                default: next_state = -1; break;\n");
    code.push_str("            }\n\n");

    code.push_str("            if (next_state == -1) { lexer->current = before; break; }\n");
    code.push_str("            state = next_state;\n\n");

    // Check if current state is accepting
    code.push_str("            switch (state) {\n");
    for state in &dfa.states {
        if state.is_accepting {
            if let Some(rule_idx) = state.rule_index {
                code.push_str(&format!("                case {}: last_accepting_state = {}; last_accepting_rule = {}; last_accepting_pos = lexer->current; break;\n", 
                    state.id, state.id, rule_idx));
            }
        }
    }
    code.push_str("                default: break;\n");
    code.push_str("            }\n");
    code.push_str("        }\n\n");

    // Handle match result
    code.push_str("        if (last_accepting_rule >= 0) {\n");
    code.push_str("            lexer->current = last_accepting_pos;\n");
    code.push_str("            TokenType tt = rule_to_token(last_accepting_rule);\n");
    code.push_str("            if (tt == TOKEN_EOF) {\n");
    code.push_str("                // Skip token, continue\n");
    code.push_str("                continue;\n");
    code.push_str("            }\n");
    code.push_str("            token.type = tt;\n");
    code.push_str("            token.start = start;\n");
    code.push_str("            token.length = (int)(last_accepting_pos - start);\n");
    code.push_str("            return token;\n");
    code.push_str("        } else {\n");
    code.push_str("            // No match, error\n");
    code.push_str("            token.type = TOKEN_ERROR;\n");
    code.push_str("            token.start = start;\n");
    code.push_str("            token.length = 1;\n");
    code.push_str("            lexer->current = start + 1;\n");
    code.push_str("            return token;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    token.type = TOKEN_EOF;\n");
    code.push_str("    return token;\n");
    code.push_str("}\n");

    // Built-in test driver
    code.push_str("\n");
    code.push_str(&generate_c_test_driver());

    Ok(code)
}

fn generate_java_full(dfa: &Dfa, spec: &LexerSpec) -> Result<String> {
    let mut code = String::new();

    code.push_str("import java.util.HashMap;\n");
    code.push_str("import java.util.Map;\n\n");

    code.push_str("public class Lexer {\n");

    // Generate token type enum
    code.push_str("    public enum TokenType {\n");
    code.push_str("        EOF,\n");
    code.push_str("        ERROR,\n");
    let mut seen_tokens = std::collections::HashSet::new();
    seen_tokens.insert("EOF".to_string());
    seen_tokens.insert("ERROR".to_string());
    for rule in &spec.rules {
        if let RuleAction::Token(name) = &rule.action {
            let upper = name.to_uppercase();
            if seen_tokens.insert(upper.clone()) {
                code.push_str(&format!("        {},\n", upper));
            }
        }
    }
    code.push_str("    }\n\n");

    // Token class with position tracking
    code.push_str("    public static class Token {\n");
    code.push_str("        public TokenType type;\n");
    code.push_str("        public String text;\n");
    code.push_str("        public int pos;\n");
    code.push_str("        public int line;\n");
    code.push_str("        public int column;\n");
    code.push_str(
        "        public Token(TokenType type, String text, int pos, int line, int column) {\n",
    );
    code.push_str("            this.type = type;\n");
    code.push_str("            this.text = text;\n");
    code.push_str("            this.pos = pos;\n");
    code.push_str("            this.line = line;\n");
    code.push_str("            this.column = column;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Lexer fields with line/column tracking
    code.push_str("    private String input;\n");
    code.push_str("    private int pos;\n");
    code.push_str("    private int line = 1;\n");
    code.push_str("    private int column = 1;\n");
    code.push_str(
        "    private static final Map<Integer, Integer> ACCEPTING = new HashMap<>();\n\n",
    );

    // Generate transition method using range comparisons
    code.push_str("    private static int getNextState(int state, int codepoint) {\n");
    code.push_str("        switch (state) {\n");
    for state in &dfa.states {
        code.push_str(&format!("            case {}:\n", state.id));
        if !state.range_transitions.is_empty() {
            for &(start_cp, end_cp, target) in &state.range_transitions {
                if start_cp == end_cp {
                    code.push_str(&format!(
                        "                if (codepoint == 0x{:X}) return {};\n",
                        start_cp, target
                    ));
                } else {
                    code.push_str(&format!("                if (codepoint >= 0x{:X} && codepoint <= 0x{:X}) return {};\n", start_cp, end_cp, target));
                }
            }
            code.push_str("                return -1;\n");
        } else if !state.transitions.is_empty() {
            // Fallback to char-based
            for (ch, target) in &state.transitions {
                let cp = *ch as u32;
                code.push_str(&format!(
                    "                if (codepoint == 0x{:X}) return {};\n",
                    cp, target
                ));
            }
            code.push_str("                return -1;\n");
        } else {
            code.push_str("                return -1;\n");
        }
    }
    code.push_str("            default: return -1;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Static initializer for accepting states
    code.push_str("    static {\n");
    for state in &dfa.states {
        if state.is_accepting {
            if let Some(rule_idx) = state.rule_index {
                code.push_str(&format!(
                    "        ACCEPTING.put({}, {});\n",
                    state.id, rule_idx
                ));
            }
        }
    }
    code.push_str("    }\n\n");

    // Constructor
    code.push_str("    public Lexer(String input) {\n");
    code.push_str("        this.input = input;\n");
    code.push_str("        this.pos = 0;\n");
    code.push_str("    }\n\n");

    // Rule to token mapping
    code.push_str("    private TokenType ruleToToken(int ruleIndex) {\n");
    code.push_str("        switch (ruleIndex) {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        match &rule.action {
            RuleAction::Token(name) => {
                code.push_str(&format!(
                    "            case {}: return TokenType.{};\n",
                    idx,
                    name.to_uppercase()
                ));
            }
            RuleAction::TokenAndBegin(name, _) => {
                code.push_str(&format!(
                    "            case {}: return TokenType.{};\n",
                    idx,
                    name.to_uppercase()
                ));
            }
            RuleAction::Skip | RuleAction::Begin(_) => {
                code.push_str(&format!(
                    "            case {}: return TokenType.EOF; // Skip or state change\n",
                    idx
                ));
            }
            RuleAction::Error => {
                code.push_str(&format!(
                    "            case {}: return TokenType.ERROR;\n",
                    idx
                ));
            }
            RuleAction::Code(_) => {
                code.push_str(&format!("            case {}: return TokenType.EOF; // Code action handled separately\n", idx));
            }
        }
    }
    code.push_str("            default: return TokenType.ERROR;\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // nextToken method - using range-based transitions with line/column tracking
    code.push_str("    public Token nextToken() {\n");
    code.push_str("        while (pos < input.length()) {\n");
    code.push_str("            int start = pos;\n");
    code.push_str("            int startLine = line;\n");
    code.push_str("            int startColumn = column;\n");
    code.push_str("            int state = 0;\n");
    code.push_str("            int lastAcceptingRule = -1;\n");
    code.push_str("            int lastAcceptingPos = start;\n");
    code.push_str("            int lastAcceptingLine = line;\n");
    code.push_str("            int lastAcceptingColumn = column;\n\n");

    code.push_str("            while (pos < input.length()) {\n");
    code.push_str("                int codepoint = input.codePointAt(pos);\n");
    code.push_str("                int nextState = getNextState(state, codepoint);\n");
    code.push_str("                if (nextState == -1) break;\n\n");
    code.push_str("                state = nextState;\n");
    code.push_str("                pos += Character.charCount(codepoint);\n");
    code.push_str(
        "                if (codepoint == '\\n') { line++; column = 1; } else { column++; }\n\n",
    );
    code.push_str("                Integer ruleIdx = ACCEPTING.get(state);\n");
    code.push_str("                if (ruleIdx != null) {\n");
    code.push_str("                    lastAcceptingRule = ruleIdx;\n");
    code.push_str("                    lastAcceptingPos = pos;\n");
    code.push_str("                    lastAcceptingLine = line;\n");
    code.push_str("                    lastAcceptingColumn = column;\n");
    code.push_str("                }\n");
    code.push_str("            }\n\n");

    code.push_str("            if (lastAcceptingRule >= 0) {\n");
    code.push_str("                pos = lastAcceptingPos;\n");
    code.push_str("                line = lastAcceptingLine;\n");
    code.push_str("                column = lastAcceptingColumn;\n");
    code.push_str("                TokenType tt = ruleToToken(lastAcceptingRule);\n");
    code.push_str("                if (tt == TokenType.EOF) continue; // Skip\n");
    code.push_str("                return new Token(tt, input.substring(start, lastAcceptingPos), start, startLine, startColumn);\n");
    code.push_str("            } else {\n");
    code.push_str("                pos = start + 1;\n");
    code.push_str("                int cp = input.codePointAt(start);\n");
    code.push_str("                if (cp == '\\n') { line++; column = 1; } else { column++; }\n");
    code.push_str("                return new Token(TokenType.ERROR, input.substring(start, pos), start, startLine, startColumn);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        return new Token(TokenType.EOF, \"\", pos, line, column);\n");
    code.push_str("    }\n");

    // Built-in test driver
    code.push_str("\n");
    code.push_str(&generate_java_test_driver());

    code.push_str("}\n");

    Ok(code)
}

fn generate_python_full(dfa: &Dfa, spec: &LexerSpec) -> Result<String> {
    let mut code = String::new();

    code.push_str("\"\"\"Lexer generated by OpenLexer with Unicode support.\"\"\"\n\n");
    code.push_str("from enum import Enum, auto\n");
    code.push_str("from dataclasses import dataclass\n");
    code.push_str("from typing import Optional, List, Tuple\n\n");

    // Token type enum
    code.push_str("class TokenType(Enum):\n");
    code.push_str("    EOF = auto()\n");
    code.push_str("    ERROR = auto()\n");
    let mut seen_tokens = std::collections::HashSet::new();
    seen_tokens.insert("EOF".to_string());
    seen_tokens.insert("ERROR".to_string());
    for rule in &spec.rules {
        if let RuleAction::Token(name) = &rule.action {
            let upper = name.to_uppercase();
            if seen_tokens.insert(upper.clone()) {
                code.push_str(&format!("    {} = auto()\n", upper));
            }
        }
    }
    code.push_str("\n\n");

    // Token dataclass
    code.push_str("@dataclass\n");
    code.push_str("class Token:\n");
    code.push_str("    type: TokenType\n");
    code.push_str("    text: str\n");
    code.push_str("    pos: int\n");
    code.push_str("    line: int = 1\n");
    code.push_str("    column: int = 1\n\n");

    // Rule to token mapping
    code.push_str("RULE_TO_TOKEN = {\n");
    for (idx, rule) in spec.rules.iter().enumerate() {
        match &rule.action {
            RuleAction::Token(name) => {
                code.push_str(&format!(
                    "    {}: TokenType.{},\n",
                    idx,
                    name.to_uppercase()
                ));
            }
            RuleAction::TokenAndBegin(name, _) => {
                code.push_str(&format!(
                    "    {}: TokenType.{},\n",
                    idx,
                    name.to_uppercase()
                ));
            }
            RuleAction::Skip | RuleAction::Begin(_) => {
                code.push_str(&format!("    {}: None,  # Skip or state change\n", idx));
            }
            RuleAction::Error => {
                code.push_str(&format!("    {}: TokenType.ERROR,\n", idx));
            }
            RuleAction::Code(_) => {
                code.push_str(&format!(
                    "    {}: None,  # Code action handled separately\n",
                    idx
                ));
            }
        }
    }
    code.push_str("}\n\n");

    // Accepting states with rule index
    code.push_str("ACCEPTING = {\n");
    for state in &dfa.states {
        if state.is_accepting {
            if let Some(rule_idx) = state.rule_index {
                code.push_str(&format!("    {}: {},\n", state.id, rule_idx));
            }
        }
    }
    code.push_str("}\n\n");

    // Generate get_next_state function with range-based transitions
    code.push_str("def get_next_state(state: int, codepoint: int) -> int:\n");
    code.push_str("    \"\"\"Get next DFA state for given state and Unicode codepoint.\"\"\"\n");

    for state in &dfa.states {
        code.push_str(&format!("    if state == {}:\n", state.id));
        if !state.range_transitions.is_empty() {
            let mut first = true;
            for &(start_cp, end_cp, target) in &state.range_transitions {
                let keyword = if first { "if" } else { "elif" };
                first = false;
                if start_cp == end_cp {
                    code.push_str(&format!(
                        "        {} codepoint == 0x{:X}:\n",
                        keyword, start_cp
                    ));
                } else {
                    code.push_str(&format!(
                        "        {} 0x{:X} <= codepoint <= 0x{:X}:\n",
                        keyword, start_cp, end_cp
                    ));
                }
                code.push_str(&format!("            return {}\n", target));
            }
            code.push_str("        return -1\n");
        } else if !state.transitions.is_empty() {
            // Fallback to single-char transitions
            let mut first = true;
            for (ch, target) in &state.transitions {
                let keyword = if first { "if" } else { "elif" };
                first = false;
                code.push_str(&format!(
                    "        {} codepoint == 0x{:X}:\n",
                    keyword, *ch as u32
                ));
                code.push_str(&format!("            return {}\n", target));
            }
            code.push_str("        return -1\n");
        } else {
            code.push_str("        return -1\n");
        }
    }
    code.push_str("    return -1\n\n");

    // Lexer class
    code.push_str("class Lexer:\n");
    code.push_str("    def __init__(self, input_str: str):\n");
    code.push_str("        self.input = input_str\n");
    code.push_str("        self.pos = 0\n");
    code.push_str("        self.line = 1\n");
    code.push_str("        self.column = 1\n\n");

    code.push_str("    def next_token(self) -> Token:\n");
    code.push_str("        while self.pos < len(self.input):\n");
    code.push_str("            start = self.pos\n");
    code.push_str("            start_line = self.line\n");
    code.push_str("            start_column = self.column\n");
    code.push_str("            state = 0\n");
    code.push_str("            last_accepting_rule = -1\n");
    code.push_str("            last_accepting_pos = start\n");
    code.push_str("            last_accepting_line = self.line\n");
    code.push_str("            last_accepting_column = self.column\n\n");

    code.push_str("            while self.pos < len(self.input):\n");
    code.push_str("                codepoint = ord(self.input[self.pos])\n");
    code.push_str("                next_state = get_next_state(state, codepoint)\n");
    code.push_str("                if next_state == -1:\n");
    code.push_str("                    break\n");
    code.push_str("                state = next_state\n");
    code.push_str("                self.pos += 1\n");
    code.push_str("                if codepoint == 0x0A:\n");
    code.push_str("                    self.line += 1\n");
    code.push_str("                    self.column = 1\n");
    code.push_str("                else:\n");
    code.push_str("                    self.column += 1\n\n");

    code.push_str("                if state in ACCEPTING:\n");
    code.push_str("                    last_accepting_rule = ACCEPTING[state]\n");
    code.push_str("                    last_accepting_pos = self.pos\n");
    code.push_str("                    last_accepting_line = self.line\n");
    code.push_str("                    last_accepting_column = self.column\n\n");

    code.push_str("            if last_accepting_rule >= 0:\n");
    code.push_str("                self.pos = last_accepting_pos\n");
    code.push_str("                self.line = last_accepting_line\n");
    code.push_str("                self.column = last_accepting_column\n");
    code.push_str("                token_type = RULE_TO_TOKEN.get(last_accepting_rule)\n");
    code.push_str("                if token_type is None:  # Skip\n");
    code.push_str("                    continue\n");
    code.push_str("                return Token(token_type, self.input[start:last_accepting_pos], start, start_line, start_column)\n");
    code.push_str("            else:\n");
    code.push_str("                self.pos = start + 1\n");
    code.push_str("                cp = ord(self.input[start])\n");
    code.push_str("                if cp == 0x0A:\n");
    code.push_str("                    self.line += 1\n");
    code.push_str("                    self.column = 1\n");
    code.push_str("                else:\n");
    code.push_str("                    self.column += 1\n");
    code.push_str("                return Token(TokenType.ERROR, self.input[start:self.pos], start, start_line, start_column)\n\n");

    code.push_str("        return Token(TokenType.EOF, '', self.pos, self.line, self.column)\n\n");

    code.push_str("    def tokenize(self):\n");
    code.push_str("        \"\"\"Generator that yields all tokens.\"\"\"\n");
    code.push_str("        while True:\n");
    code.push_str("            token = self.next_token()\n");
    code.push_str("            yield token\n");
    code.push_str("            if token.type == TokenType.EOF:\n");
    code.push_str("                break\n");

    // Built-in test driver
    code.push_str("\n\n");
    code.push_str(&generate_python_test_driver());

    Ok(code)
}

// =============================================================================
// Simple single-pattern lexer generation (legacy)
// =============================================================================

fn generate_c_simple(dfa: &Dfa) -> Result<String> {
    let mut code = String::new();

    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdbool.h>\n\n");
    code.push_str("typedef enum { TOKEN_INVALID, TOKEN_MATCH } TokenType;\n\n");

    code.push_str("TokenType lex(const char* input) {\n");
    code.push_str("    int state = 0;\n");
    code.push_str("    const char* c = input;\n");
    code.push_str("    while (*c != '\\0') {\n");
    code.push_str("        switch (state) {\n");

    for state in &dfa.states {
        code.push_str(&format!("            case {}:\n", state.id));
        code.push_str("                switch (*c) {\n");
        for (ch, target) in &state.transitions {
            let escaped = escape_c_char(*ch);
            code.push_str(&format!(
                "                    case {}: state = {}; break;\n",
                escaped, target
            ));
        }
        code.push_str("                    default: return TOKEN_INVALID;\n");
        code.push_str("                }\n");
        code.push_str("                break;\n");
    }

    code.push_str("        }\n");
    code.push_str("        c++;\n");
    code.push_str("    }\n\n");

    code.push_str("    switch (state) {\n");
    for state in &dfa.states {
        if state.is_accepting {
            code.push_str(&format!("        case {}: return TOKEN_MATCH;\n", state.id));
        }
    }
    code.push_str("        default: return TOKEN_INVALID;\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    Ok(code)
}

fn generate_java_simple(dfa: &Dfa) -> Result<String> {
    let mut code = String::new();
    code.push_str("public class Lexer {\n");
    code.push_str("    public enum TokenType { INVALID, MATCH }\n\n");
    code.push_str("    public static TokenType lex(String input) {\n");
    code.push_str("        int state = 0;\n");
    code.push_str("        for (int i = 0; i < input.length(); i++) {\n");
    code.push_str("            char c = input.charAt(i);\n");
    code.push_str("            switch (state) {\n");

    for state in &dfa.states {
        code.push_str(&format!("                case {}:\n", state.id));
        code.push_str("                    switch (c) {\n");
        for (ch, target) in &state.transitions {
            let escaped = escape_java_char(*ch);
            code.push_str(&format!(
                "                        case {}: state = {}; break;\n",
                escaped, target
            ));
        }
        code.push_str("                        default: return TokenType.INVALID;\n");
        code.push_str("                    }\n");
        code.push_str("                    break;\n");
    }

    code.push_str("            }\n");
    code.push_str("        }\n\n");

    code.push_str("        switch (state) {\n");
    for state in &dfa.states {
        if state.is_accepting {
            code.push_str(&format!(
                "            case {}: return TokenType.MATCH;\n",
                state.id
            ));
        }
    }
    code.push_str("            default: return TokenType.INVALID;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    Ok(code)
}

fn generate_python_simple(dfa: &Dfa) -> Result<String> {
    let mut code = String::new();

    code.push_str("class TokenType:\n");
    code.push_str("    INVALID = 0\n");
    code.push_str("    MATCH = 1\n\n");

    code.push_str("def lex(input_str):\n");
    code.push_str("    \"\"\"Lexer function generated by OpenLexer.\"\"\"\n");

    code.push_str("    transitions = {\n");
    for state in &dfa.states {
        code.push_str(&format!("        {}: {{", state.id));
        for (ch, target) in &state.transitions {
            let escaped = escape_python_char(*ch);
            code.push_str(&format!("'{}': {}, ", escaped, target));
        }
        code.push_str("},\n");
    }
    code.push_str("    }\n\n");

    let accepting: Vec<String> = dfa
        .states
        .iter()
        .filter(|s| s.is_accepting)
        .map(|s| s.id.to_string())
        .collect();
    code.push_str(&format!(
        "    accepting_states = {{{}}}\n\n",
        accepting.join(", ")
    ));

    code.push_str("    state = 0\n");
    code.push_str("    for c in input_str:\n");
    code.push_str("        state_transitions = transitions.get(state)\n");
    code.push_str("        if state_transitions is None:\n");
    code.push_str("            return TokenType.INVALID\n");
    code.push_str("        next_state = state_transitions.get(c)\n");
    code.push_str("        if next_state is None:\n");
    code.push_str("            return TokenType.INVALID\n");
    code.push_str("        state = next_state\n\n");

    code.push_str(
        "    return TokenType.MATCH if state in accepting_states else TokenType.INVALID\n",
    );

    Ok(code)
}

// =============================================================================
// Built-in Test Drivers
// =============================================================================

/// Generates a standalone Python test driver.
/// Can be appended to a generated lexer or written as a separate file.
pub fn generate_python_test_driver() -> String {
    let mut code = String::new();
    code.push_str("def test(expr: str):\n");
    code.push_str("    \"\"\"Test the lexer with an expression. Prints all tokens found.\"\"\"\n");
    code.push_str("    print(f\"Input: {expr!r}\")\n");
    code.push_str("    lexer = Lexer(expr)\n");
    code.push_str("    tokens = []\n");
    code.push_str("    for token in lexer.tokenize():\n");
    code.push_str("        tokens.append(token)\n");
    code.push_str("        if hasattr(token, 'line'):\n");
    code.push_str("            print(f\"  {token.type.name:12s} | {token.text!r:15s} | pos={token.pos} line={token.line} col={token.column}\")\n");
    code.push_str("        else:\n");
    code.push_str(
        "            print(f\"  {token.type.name:12s} | {token.text!r:15s} | pos={token.pos}\")\n",
    );
    code.push_str("    print()\n");
    code.push_str("    return tokens\n\n\n");
    code.push_str("def test_all(*expressions):\n");
    code.push_str("    \"\"\"Test the lexer with multiple expressions.\n");
    code.push_str("    \n");
    code.push_str("    Usage:\n");
    code.push_str("        from lexer import test, test_all\n");
    code.push_str("        test('3 + 4 * 2')\n");
    code.push_str("        test_all('1+2', '(3*4)', 'hello world')\n");
    code.push_str("    \"\"\"\n");
    code.push_str("    results = []\n");
    code.push_str("    for expr in expressions:\n");
    code.push_str("        results.append(test(expr))\n");
    code.push_str("    return results\n\n\n");
    code.push_str("if __name__ == '__main__':\n");
    code.push_str("    import sys\n");
    code.push_str("    if len(sys.argv) > 1:\n");
    code.push_str("        # Test with command-line arguments\n");
    code.push_str("        for arg in sys.argv[1:]:\n");
    code.push_str("            test(arg)\n");
    code.push_str("    else:\n");
    code.push_str("        # Default demo expressions\n");
    code.push_str("        print('=== OpenLexer Test Driver ===')\n");
    code.push_str("        print('Usage: python lexer.py \"expression1\" \"expression2\" ...')\n");
    code.push_str("        print('Or:    from lexer import test, test_all')\n");
    code.push_str("        print()\n");
    code.push_str("        test('3 + 4 * 2')\n");
    code.push_str("        test('(10 - 2) / 4')\n");
    code.push_str("        test('hello world')\n");
    code.push_str("        test('')\n");
    code
}

/// Generates a standalone C test driver.
pub fn generate_c_test_driver() -> String {
    let mut code = String::new();
    code.push_str("#ifndef LEXER_NO_MAIN\n");
    code.push_str("/* === Built-in Test Driver === */\n\n");
    code.push_str("static void test(const char* expr) {\n");
    code.push_str("    printf(\"Input: \\\"%s\\\"\\n\", expr);\n");
    code.push_str("    Lexer lexer;\n");
    code.push_str("    lexer_init(&lexer, expr);\n");
    code.push_str("    Token token;\n");
    code.push_str("    do {\n");
    code.push_str("        token = lexer_next(&lexer);\n");
    code.push_str("        printf(\"  type=%-3d | \\\"\", token.type);\n");
    code.push_str("        for (int i = 0; i < token.length; i++) putchar(token.start[i]);\n");
    code.push_str("        printf(\"\\\"\\n\");\n");
    code.push_str("    } while (token.type != TOKEN_EOF);\n");
    code.push_str("    printf(\"\\n\");\n");
    code.push_str("}\n\n");
    code.push_str("int main(int argc, char** argv) {\n");
    code.push_str("    if (argc > 1) {\n");
    code.push_str("        for (int i = 1; i < argc; i++) {\n");
    code.push_str("            test(argv[i]);\n");
    code.push_str("        }\n");
    code.push_str("    } else {\n");
    code.push_str("        printf(\"=== OpenLexer Test Driver ===\\n\");\n");
    code.push_str(
        "        printf(\"Usage: ./lexer \\\"expression1\\\" \\\"expression2\\\" ...\\n\\n\");\n",
    );
    code.push_str("        test(\"3 + 4 * 2\");\n");
    code.push_str("        test(\"(10 - 2) / 4\");\n");
    code.push_str("        test(\"hello world\");\n");
    code.push_str("        test(\"\");\n");
    code.push_str("    }\n");
    code.push_str("    return 0;\n");
    code.push_str("}\n");
    code.push_str("#endif /* LEXER_NO_MAIN */\n");
    code
}

/// Generates a standalone Java test driver (methods inside the Lexer class).
pub fn generate_java_test_driver() -> String {
    let mut code = String::new();
    code.push_str("    /* === Built-in Test Driver === */\n\n");
    code.push_str("    public static void test(String expr) {\n");
    code.push_str("        System.out.printf(\"Input: \\\"%s\\\"%n\", expr);\n");
    code.push_str("        Lexer lexer = new Lexer(expr);\n");
    code.push_str("        Token token;\n");
    code.push_str("        do {\n");
    code.push_str("            token = lexer.nextToken();\n");
    code.push_str("            System.out.printf(\"  %-12s | %-15s | pos=%d line=%d col=%d%n\",\n");
    code.push_str("                token.type, \"\\\"\" + token.text.replace(\"\\n\", \"\\\\n\") + \"\\\"\", token.pos, token.line, token.column);\n");
    code.push_str("        } while (token.type != TokenType.EOF);\n");
    code.push_str("        System.out.println();\n");
    code.push_str("    }\n\n");
    code.push_str("    public static void main(String[] args) {\n");
    code.push_str("        if (args.length > 0) {\n");
    code.push_str("            for (String arg : args) {\n");
    code.push_str("                test(arg);\n");
    code.push_str("            }\n");
    code.push_str("        } else {\n");
    code.push_str("            System.out.println(\"=== OpenLexer Test Driver ===\");\n");
    code.push_str("            System.out.println(\"Usage: java Lexer \\\"expression1\\\" \\\"expression2\\\" ...\");\n");
    code.push_str("            System.out.println();\n");
    code.push_str("            test(\"3 + 4 * 2\");\n");
    code.push_str("            test(\"(10 - 2) / 4\");\n");
    code.push_str("            test(\"hello world\");\n");
    code.push_str("            test(\"\");\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code
}

/// Escape a character for use in a Python string literal.
/// Returns just the escaped character content without surrounding quotes.
/// The caller is responsible for adding quotes.
fn escape_python_char(ch: char) -> String {
    match ch {
        '\'' => "\\'".to_string(),
        '\\' => "\\\\".to_string(),
        '\n' => "\\n".to_string(),
        '\t' => "\\t".to_string(),
        '\r' => "\\r".to_string(),
        '\0' => "\\x00".to_string(),
        c if c.is_ascii_control() => format!("\\x{:02x}", c as u32),
        c => c.to_string(),
    }
}

/// Escape a character for use in a C char literal (including quotes).
/// For non-ASCII (Unicode) chars, returns an integer codepoint format.
fn escape_c_char(ch: char) -> String {
    // Non-ASCII characters can't be represented in C char literals
    // Use the codepoint value directly
    if !ch.is_ascii() {
        return format!("0x{:04X}", ch as u32);
    }

    let inner = match ch {
        '\'' => "\\'".to_string(),
        '\\' => "\\\\".to_string(),
        '\n' => "\\n".to_string(),
        '\t' => "\\t".to_string(),
        '\r' => "\\r".to_string(),
        '\0' => "\\0".to_string(),
        c if c.is_ascii_control() => format!("\\x{:02x}", c as u32),
        c => c.to_string(),
    };
    format!("'{}'", inner)
}

/// Escape a character for use in a Java char literal (including quotes).
fn escape_java_char(ch: char) -> String {
    let inner = match ch {
        '\'' => "\\'".to_string(),
        '\\' => "\\\\".to_string(),
        '\n' => "\\n".to_string(),
        '\t' => "\\t".to_string(),
        '\r' => "\\r".to_string(),
        '\0' => "\\0".to_string(),
        c if c.is_ascii_control() => format!("\\u{:04x}", c as u32),
        c if !c.is_ascii() => format!("\\u{:04x}", c as u32),
        c => c.to_string(),
    };
    format!("'{}'", inner)
}
