"""Lexer generated by OpenLexer"""

TOKEN_EOF, TOKEN_ERROR = 0, 1
TOKEN_IF = 2
TOKEN_ELSE = 3
TOKEN_OTHER = 4
TOKEN_CONDITION = 5
TOKEN_LPAREN = 6
TOKEN_RPAREN = 7

TOKEN_NAMES = {TOKEN_EOF: 'EOF', TOKEN_ERROR: 'ERROR', TOKEN_IF: 'IF', TOKEN_ELSE: 'ELSE', TOKEN_OTHER: 'OTHER', TOKEN_CONDITION: 'CONDITION', TOKEN_LPAREN: 'LPAREN', TOKEN_RPAREN: 'RPAREN'}

_TRANS = {
    0: [(0,8,1),(9,9,2),(10,10,3),(11,31,1),(32,32,2),(33,39,1),(40,40,4),(41,41,5),(42,98,1),(99,99,6),(100,100,1),(101,101,7),(102,104,1),(105,105,8),(106,110,1),(111,111,9),(112,127,1),],
    2: [(9,10,3),(32,32,3),],
    3: [(9,10,3),(32,32,3),],
    6: [(111,111,18),],
    7: [(108,108,15),],
    8: [(102,102,14),],
    9: [(116,116,10),],
    10: [(104,104,11),],
    11: [(101,101,12),],
    12: [(114,114,13),],
    15: [(115,115,16),],
    16: [(101,101,17),],
    18: [(110,110,19),],
    19: [(100,100,20),],
    20: [(105,105,21),],
    21: [(116,116,22),],
    22: [(105,105,23),],
    23: [(111,111,24),],
    24: [(110,110,25),],
}

_ACCEPT = {1: 7,2: 6,3: 6,4: 4,5: 5,6: 7,7: 7,8: 7,9: 7,13: 2,14: 0,17: 1,25: 3,}

_RULE_TOKEN = {0: TOKEN_IF,1: TOKEN_ELSE,2: TOKEN_OTHER,3: TOKEN_CONDITION,4: TOKEN_LPAREN,5: TOKEN_RPAREN,6: None,7: None,}

class Lexer:
    def __init__(self, src): self.src, self.pos = src, 0

    def next_token(self):
        while self.pos < len(self.src):
            start, state, last_rule, last_pos = self.pos, 0, -1, self.pos
            while self.pos < len(self.src):
                cp, ns = ord(self.src[self.pos]), -1
                for lo, hi, tgt in _TRANS.get(state, []):
                    if lo <= cp <= hi: ns = tgt; break
                if ns < 0: break
                state = ns; self.pos += 1
                if state in _ACCEPT: last_rule, last_pos = _ACCEPT[state], self.pos
            if last_rule >= 0:
                self.pos = last_pos
                tok = _RULE_TOKEN.get(last_rule, TOKEN_ERROR)
                if tok is None: continue
                return (tok, self.src[start:last_pos])
            self.pos = start + 1
            return (TOKEN_ERROR, self.src[start:start+1])
        return (TOKEN_EOF, '')

    def tokenize(self):
        while True:
            tok = self.next_token()
            yield tok
            if tok[0] == TOKEN_EOF: break

def test(text):
    print(f'Input: "{text}"')
    for tok, val in Lexer(text).tokenize():
        print(f'  [{TOKEN_NAMES.get(tok, tok)}] "{val}"')

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        for arg in sys.argv[1:]: test(arg)
    else:
        import sys as _sys
        _input = _sys.stdin.read().strip()
        if _input:
            for line in _input.splitlines(): test(line)
        else: test('3 + 4 * 2'); test('(10 - 2) / 4')
