# Generated by OpenLexer

class Parser:
    def __init__(self, lexer):
        self.lexer = lexer
        self.action = {
            5: {'CONDITION': ('S', 6), },
            9: {'$': ('R', 2), 'ELSE': ('S', 10), },
            4: {'$': ('A', 0), },
            0: {'OTHER': ('S', 1), 'IF': ('S', 2), },
            3: {'$': ('R', 0), },
            8: {'OTHER': ('S', 1), 'IF': ('S', 2), },
            2: {'LPAREN': ('S', 5), },
            1: {'$': ('R', 3), 'ELSE': ('R', 3), },
            6: {'RPAREN': ('R', 4), },
            7: {'RPAREN': ('S', 8), },
            10: {'OTHER': ('S', 1), 'IF': ('S', 2), },
            11: {'$': ('R', 1), 'ELSE': ('R', 1), },
        }
        self.goto = {
            0: {'program': 4, 'S': 3, },
            10: {'S': 11, },
            8: {'S': 9, },
            5: {'E': 7, },
        }
        self.rules = [
            ('program', 1),
            ('S', 7),
            ('S', 5),
            ('S', 1),
            ('E', 1),
        ]

    def parse(self):
        state_stack = [0]
        value_stack = [None]  # Semantic values
        sym = self.lexer.next_token()
        
        while True:
            state = state_stack[-1]
            token_type = sym.type if hasattr(sym, 'type') else str(sym)
            
            if state not in self.action or token_type not in self.action[state]:
                raise SyntaxError(f'Unexpected token {sym} in state {state}')
            
            act, param = self.action[state][token_type]
            
            if act == 'S':  # Shift
                state_stack.append(param)
                # Push token value onto value stack
                value_stack.append(getattr(sym, 'value', sym.text if hasattr(sym, 'text') else sym))
                sym = self.lexer.next_token()
                
            elif act == 'R':  # Reduce
                lhs, length = self.rules[param]
                
                # Get values from stack for semantic action
                if length > 0:
                    vals = value_stack[-length:]
                else:
                    vals = []
                
                # Default: result = first value or None
                result = vals[0] if vals else None
                
                # Semantic action by rule
                rule_id = param
                if rule_id == 0:
                    print("Parse complete.")
                if rule_id == 1:
                    print("if-else statement")
                if rule_id == 2:
                    print("if statement")
                if rule_id == 3:
                    print("other")
                if rule_id == 4:
                    print("condition")
                
                # Pop stacks
                for _ in range(length):
                    state_stack.pop()
                    value_stack.pop()
                
                # Push result and goto state
                top = state_stack[-1]
                if top in self.goto and lhs in self.goto[top]:
                    state_stack.append(self.goto[top][lhs])
                    value_stack.append(result)
                else:
                    raise SyntaxError(f'No goto for {lhs} from state {top}')
                    
            elif act == 'A':  # Accept
                return value_stack[-1] if len(value_stack) > 1 else None


# =============================================================================
# Combined Lexer + Parser Test Driver
# =============================================================================

class LexerAdapter:
    """Adapts a lexer to work with the parser.
    
    Usage:
        from lexer import Lexer, TokenType
        from parser import Parser, LexerAdapter
        
        adapter = LexerAdapter(Lexer('3 + 4 * 2'))
        parser = Parser(adapter)
        result = parser.parse()
    """
    def __init__(self, lexer):
        self.lexer = lexer
    
    def next_token(self):
        tok = self.lexer.next_token()
        # Return adapted token with string type name
        return AdaptedToken(tok)


class AdaptedToken:
    """Token adapter for parser compatibility."""
    def __init__(self, tok):
        # Convert enum to parser terminal names ('$' for EOF)
        raw_type = tok.type.name
        token_aliases = {
            'EOF': '$',
            'INTEGER_LITERAL': 'NUMBER',
            'INT_LITERAL': 'NUMBER',
            'NUM_LITERAL': 'NUMBER',
            'FLOAT_LITERAL': 'NUMBER',
        }
        self.type = token_aliases.get(raw_type, raw_type)
        self.text = tok.text
        self.pos = tok.pos
        # Extract numeric value for NUMBER tokens
        try:
            self.value = int(tok.text) if tok.text.isdigit() else tok.text
        except:
            self.value = tok.text


def parse_expression(expr: str, lexer_class=None):
    """Parse an expression string and return the result.
    
    Args:
        expr: The expression to parse
        lexer_class: Optional custom Lexer class (defaults to imported Lexer)
    
    Returns:
        The parse result (semantic value from reduction)
    
    Example:
        >>> parse_expression('3 + 4')
        7
    """
    if lexer_class is not None:
        LexerClass = lexer_class
    else:
        import importlib
        import importlib.util
        from pathlib import Path

        LexerClass = None
        # 1) Try normal module imports (both common naming conventions)
        for module_name in ('lexer', 'Lexer'):
            try:
                mod = importlib.import_module(module_name)
                if hasattr(mod, 'Lexer'):
                    LexerClass = getattr(mod, 'Lexer')
                    break
            except Exception:
                pass

        # 2) Try loading sibling files next to this parser file
        if LexerClass is None:
            base_dir = Path(__file__).resolve().parent if '__file__' in globals() else Path.cwd()
            for filename in ('lexer.py', 'Lexer.py'):
                path = base_dir / filename
                if not path.exists():
                    continue
                spec = importlib.util.spec_from_file_location(path.stem, str(path))
                if spec is None or spec.loader is None:
                    continue
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                if hasattr(mod, 'Lexer'):
                    LexerClass = getattr(mod, 'Lexer')
                    break

        if LexerClass is None:
            raise ImportError('Could not import Lexer. Checked modules lexer/Lexer and sibling files lexer.py/Lexer.py.')
    
    adapter = LexerAdapter(LexerClass(expr))
    parser = Parser(adapter)
    return parser.parse()


def test_parse(expr: str):
    """Test parsing an expression and print the result."""
    print(f'Parsing: {expr!r}')
    try:
        result = parse_expression(expr)
        print(f'  Result: {result}')
        return result
    except Exception as e:
        print(f'  Error: {e}')
        return None


if __name__ == '__main__':
    import sys
    print('=== OpenLexer Parser Test Driver ===')
    print()
    
    if len(sys.argv) > 1:
        for arg in sys.argv[1:]:
            test_parse(arg)
    else:
        _input = sys.stdin.read().strip()
        if _input:
            for line in _input.splitlines():
                test_parse(line)
        else:
            test_parse('3 + 4')
            test_parse('3 + 4 * 2')
