/* Generated by OpenLexer */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Default semantic value type */
typedef int YYSTYPE;

/* Dynamic parser stack */
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000

typedef struct {
    int state;
    YYSTYPE value;
} yystack_item;

static yystack_item *yystack = NULL;
static int yystack_capacity = 0;
static int yytop = 0;

static int yygrow_stack(int needed) {
    if (needed > YYMAXDEPTH) {
        return -1; /* Stack overflow */
    }
    if (needed > yystack_capacity) {
        int new_cap = yystack_capacity ? yystack_capacity * 2 : YYINITDEPTH;
        while (new_cap < needed) new_cap *= 2;
        if (new_cap > YYMAXDEPTH) new_cap = YYMAXDEPTH;
        yystack_item *new_stack = (yystack_item *)realloc(yystack, new_cap * sizeof(yystack_item));
        if (!new_stack) return -1;
        yystack = new_stack;
        yystack_capacity = new_cap;
    }
    return 0;
}

static int yypush(int state, YYSTYPE value) {
    if (yygrow_stack(yytop + 2) != 0) {
        fprintf(stderr, "Parser stack overflow\n");
        return -1;
    }
    yytop++;
    yystack[yytop].state = state;
    yystack[yytop].value = value;
    return 0;
}

static int yypop(int n) {
    yytop -= n;
    return (yytop >= 0) ? yystack[yytop].state : 0;
}

static void yyfree_stack(void) {
    free(yystack);
    yystack = NULL;
    yystack_capacity = 0;
    yytop = 0;
}

// Action: 0=Error, 1=Shift, 2=Reduce, 3=Accept
void get_action(int state, const char* token, int* type, int* param) {
    *type = 0; *param = 0;
    if (state == 9) {
        if (strcmp(token, "OTHER") == 0) { *type = 1; *param = 2; return; }
        if (strcmp(token, "IF") == 0) { *type = 1; *param = 1; return; }
    }
    if (state == 7) {
        if (strcmp(token, "IF") == 0) { *type = 1; *param = 1; return; }
        if (strcmp(token, "OTHER") == 0) { *type = 1; *param = 2; return; }
    }
    if (state == 1) {
        if (strcmp(token, "LPAREN") == 0) { *type = 1; *param = 4; return; }
    }
    if (state == 8) {
        if (strcmp(token, "$") == 0) { *type = 2; *param = 1; return; }
        if (strcmp(token, "ELSE") == 0) { *type = 1; *param = 9; return; }
    }
    if (state == 6) {
        if (strcmp(token, "RPAREN") == 0) { *type = 2; *param = 3; return; }
    }
    if (state == 4) {
        if (strcmp(token, "CONDITION") == 0) { *type = 1; *param = 6; return; }
    }
    if (state == 2) {
        if (strcmp(token, "ELSE") == 0) { *type = 2; *param = 2; return; }
        if (strcmp(token, "$") == 0) { *type = 2; *param = 2; return; }
    }
    if (state == 5) {
        if (strcmp(token, "RPAREN") == 0) { *type = 1; *param = 7; return; }
    }
    if (state == 10) {
        if (strcmp(token, "$") == 0) { *type = 2; *param = 0; return; }
        if (strcmp(token, "ELSE") == 0) { *type = 2; *param = 0; return; }
    }
    if (state == 0) {
        if (strcmp(token, "IF") == 0) { *type = 1; *param = 1; return; }
        if (strcmp(token, "OTHER") == 0) { *type = 1; *param = 2; return; }
    }
    if (state == 3) {
        if (strcmp(token, "$") == 0) { *type = 3; *param = 0; return; }
    }
}

int get_goto(int state, const char* lhs) {
    if (state == 4) {
        if (strcmp(lhs, "E") == 0) return 5;
    }
    if (state == 9) {
        if (strcmp(lhs, "S") == 0) return 10;
    }
    if (state == 7) {
        if (strcmp(lhs, "S") == 0) return 8;
    }
    if (state == 0) {
        if (strcmp(lhs, "S") == 0) return 3;
    }
    return -1;
}

void get_rule(int id, char** lhs, int* len) {
    switch(id) {
        case 0: *lhs = "S"; *len = 7; break;
        case 1: *lhs = "S"; *len = 5; break;
        case 2: *lhs = "S"; *len = 1; break;
        case 3: *lhs = "E"; *len = 1; break;
    }
}

YYSTYPE yylval;

/* Error recovery support */
#define yyerrok  (yyerrstatus = 0)
#define yyclearin (yychar = -1)
static int yynerrs = 0;
static int yyerrstatus = 0;
static int yychar = -1;

/* External lexer function - user must provide */
extern int yylex(void);
extern char *yytext;
extern int yyleng;

static const char* yytokenname(int token) {
    switch(token) {
        case 256: return "IF";
        case 257: return "LPAREN";
        case 258: return "RPAREN";
        case 259: return "ELSE";
        case 260: return "OTHER";
        case 261: return "CONDITION";
        case 0: return "$";
        default: return "unknown";
    }
}

#define YYNTOKENS 7
static const int yytokens[] = {0, 256, 257, 258, 259, 260, 261};

void yyerror(const char *msg) {
    fprintf(stderr, "%s\n", msg);
    yynerrs++;
}

int yyparse(void) {
    /* Initialize stack */
    if (yygrow_stack(YYINITDEPTH) != 0) {
        fprintf(stderr, "Out of memory\n");
        return 2;
    }
    yytop = 0;
    yystack[0].state = 0;
    memset(&yystack[0].value, 0, sizeof(YYSTYPE));

    int yytoken = yylex();
    int action_type, action_param;
    char *lhs_name;
    int rhs_len;
    YYSTYPE yyval;

    while (1) {
        int state = yystack[yytop].state;
        get_action(state, yytokenname(yytoken), &action_type, &action_param);

        if (action_type == 0) { /* Error */
            yyerror("syntax error");
            yyfree_stack();
            return 1;
        }

        if (action_type == 1) { /* Shift */
            if (yypush(action_param, yylval) != 0) {
                yyfree_stack();
                return 2;
            }
            yytoken = yylex();
        }

        else if (action_type == 2) { /* Reduce */
            get_rule(action_param, &lhs_name, &rhs_len);
            memset(&yyval, 0, sizeof(YYSTYPE));
            if (rhs_len > 0) {
                yyval = yystack[yytop - (rhs_len - 1)].value; /* Default: $$ = $1 */
            }

            /* Semantic Actions */
            switch(action_param) {
            }

            yypop(rhs_len);
            int goto_state = get_goto(yystack[yytop].state, lhs_name);
            if (goto_state == -1) {
                yyerror("internal goto error");
                yyfree_stack();
                return 1;
            }
            if (yypush(goto_state, yyval) != 0) {
                yyfree_stack();
                return 2;
            }
        }

        else if (action_type == 3) { /* Accept */
            yyfree_stack();
            return 0;
        }
    }
}

/* =============================================================================
 * Combined Lexer + Parser Test Driver
 * 
 * To use with generated lexer:
 *   1. Generate lexer: openlexer gen-lexer -l grammar.l -L c -o output/
 *   2. Generate parser: openlexer gen-parser --parser grammar.y -L c -o output/
 *   3. Compile both: gcc -o parser lexer.c parser.c -DPARSER_NO_MAIN
 *   4. Or use the built-in test below
 * ============================================================================= */

#ifndef PARSER_NO_MAIN
/* Extern declarations for lexer integration */
extern int yylex(void);  /* Returns token type, sets yylval */
extern YYSTYPE yylval;   /* Semantic value from lexer */

int main(int argc, char **argv) {
    printf("=== OpenLexer Parser Test ===\n");
    int result = yyparse();
    if (result == 0) {
        printf("Parse successful!\n");
    } else {
        printf("Parse failed with code %d\n", result);
    }
    return result;
}
#endif /* PARSER_NO_MAIN */
