# Generated by OpenLexer

class Parser:
    def __init__(self, lexer):
        self.lexer = lexer
        self.action = {
            15: {'PLUS': ('R', 14), 'DIVIDE': ('R', 14), 'POWER': ('R', 14), 'MOD': ('R', 14), 'RPAREN': ('R', 14), 'TIMES': ('R', 14), 'MINUS': ('R', 14), 'NEWLINE': ('R', 14), },
            8: {'MINUS': ('S', 8), 'LPAREN': ('S', 2), 'NUMBER': ('S', 5), },
            22: {'NUMBER': ('S', 5), 'MINUS': ('S', 8), 'LPAREN': ('S', 2), },
            3: {'MINUS': ('S', 24), 'NEWLINE': ('S', 23), 'PLUS': ('S', 22), },
            6: {'MINUS': ('R', 5), 'TIMES': ('S', 16), 'DIVIDE': ('S', 17), 'MOD': ('S', 18), 'PLUS': ('R', 5), 'NEWLINE': ('R', 5), 'RPAREN': ('R', 5), },
            7: {'NEWLINE': ('R', 1), 'NUMBER': ('R', 1), '$': ('R', 1), 'LPAREN': ('R', 1), 'MINUS': ('R', 1), },
            21: {'RPAREN': ('R', 9), 'DIVIDE': ('R', 9), 'POWER': ('S', 13), 'MINUS': ('R', 9), 'TIMES': ('R', 9), 'MOD': ('R', 9), 'NEWLINE': ('R', 9), 'PLUS': ('R', 9), },
            26: {'NEWLINE': ('R', 6), 'TIMES': ('S', 16), 'PLUS': ('R', 6), 'RPAREN': ('R', 6), 'MOD': ('S', 18), 'DIVIDE': ('S', 17), 'MINUS': ('R', 6), },
            1: {'MINUS': ('S', 8), 'NUMBER': ('S', 5), 'LPAREN': ('S', 2), 'NEWLINE': ('S', 4), '$': ('A', 0), },
            16: {'MINUS': ('S', 8), 'LPAREN': ('S', 2), 'NUMBER': ('S', 5), },
            11: {'TIMES': ('R', 12), 'NEWLINE': ('R', 12), 'MINUS': ('R', 12), 'DIVIDE': ('R', 12), 'MOD': ('R', 12), 'PLUS': ('R', 12), 'POWER': ('R', 12), 'RPAREN': ('R', 12), },
            5: {'TIMES': ('R', 15), 'MINUS': ('R', 15), 'MOD': ('R', 15), 'RPAREN': ('R', 15), 'POWER': ('R', 15), 'DIVIDE': ('R', 15), 'NEWLINE': ('R', 15), 'PLUS': ('R', 15), },
            9: {'MOD': ('R', 8), 'TIMES': ('R', 8), 'PLUS': ('R', 8), 'NEWLINE': ('R', 8), 'DIVIDE': ('R', 8), 'MINUS': ('R', 8), 'RPAREN': ('R', 8), 'POWER': ('S', 13), },
            27: {'PLUS': ('S', 22), 'MINUS': ('S', 24), 'RPAREN': ('S', 28), },
            20: {'POWER': ('S', 13), 'PLUS': ('R', 10), 'NEWLINE': ('R', 10), 'TIMES': ('R', 10), 'DIVIDE': ('R', 10), 'MOD': ('R', 10), 'MINUS': ('R', 10), 'RPAREN': ('R', 10), },
            25: {'PLUS': ('R', 7), 'DIVIDE': ('S', 17), 'NEWLINE': ('R', 7), 'RPAREN': ('R', 7), 'MOD': ('S', 18), 'MINUS': ('R', 7), 'TIMES': ('S', 16), },
            24: {'NUMBER': ('S', 5), 'MINUS': ('S', 8), 'LPAREN': ('S', 2), },
            12: {'NUMBER': ('R', 4), 'MINUS': ('R', 4), 'LPAREN': ('R', 4), '$': ('R', 4), 'NEWLINE': ('R', 4), },
            17: {'NUMBER': ('S', 5), 'LPAREN': ('S', 2), 'MINUS': ('S', 8), },
            19: {'RPAREN': ('R', 11), 'POWER': ('S', 13), 'MINUS': ('R', 11), 'MOD': ('R', 11), 'NEWLINE': ('R', 11), 'TIMES': ('R', 11), 'DIVIDE': ('R', 11), 'PLUS': ('R', 11), },
            28: {'DIVIDE': ('R', 16), 'NEWLINE': ('R', 16), 'TIMES': ('R', 16), 'PLUS': ('R', 16), 'MINUS': ('R', 16), 'POWER': ('R', 16), 'MOD': ('R', 16), 'RPAREN': ('R', 16), },
            14: {'MOD': ('R', 13), 'POWER': ('R', 13), 'PLUS': ('R', 13), 'MINUS': ('R', 13), 'DIVIDE': ('R', 13), 'NEWLINE': ('R', 13), 'TIMES': ('R', 13), 'RPAREN': ('R', 13), },
            18: {'LPAREN': ('S', 2), 'NUMBER': ('S', 5), 'MINUS': ('S', 8), },
            10: {'NEWLINE': ('S', 12), },
            4: {'NUMBER': ('R', 2), 'NEWLINE': ('R', 2), '$': ('R', 2), 'LPAREN': ('R', 2), 'MINUS': ('R', 2), },
            13: {'LPAREN': ('S', 2), 'NUMBER': ('S', 5), },
            23: {'MINUS': ('R', 3), 'LPAREN': ('R', 3), '$': ('R', 3), 'NEWLINE': ('R', 3), 'NUMBER': ('R', 3), },
            0: {'NUMBER': ('R', 0), 'LPAREN': ('R', 0), '$': ('R', 0), 'MINUS': ('R', 0), 'NEWLINE': ('R', 0), },
            2: {'NUMBER': ('S', 5), 'LPAREN': ('S', 2), 'MINUS': ('S', 8), },
        }
        self.goto = {
            1: {'error': 10, 'expr': 3, 'term': 6, 'factor': 9, 'primary': 11, 'line': 7, },
            13: {'primary': 14, },
            0: {'input': 1, },
            8: {'primary': 11, 'factor': 15, },
            24: {'factor': 9, 'term': 25, 'primary': 11, },
            22: {'term': 26, 'factor': 9, 'primary': 11, },
            2: {'term': 6, 'factor': 9, 'primary': 11, 'expr': 27, },
            17: {'factor': 20, 'primary': 11, },
            16: {'primary': 11, 'factor': 21, },
            18: {'factor': 19, 'primary': 11, },
        }
        self.rules = [
            ('input', 0),
            ('input', 2),
            ('line', 1),
            ('line', 2),
            ('line', 2),
            ('expr', 1),
            ('expr', 3),
            ('expr', 3),
            ('term', 1),
            ('term', 3),
            ('term', 3),
            ('term', 3),
            ('factor', 1),
            ('factor', 3),
            ('factor', 2),
            ('primary', 1),
            ('primary', 3),
        ]

    def parse(self):
        state_stack = [0]
        value_stack = [None]  # Semantic values
        sym = self.lexer.next_token()
        
        while True:
            state = state_stack[-1]
            token_type = sym.type if hasattr(sym, 'type') else str(sym)
            
            if state not in self.action or token_type not in self.action[state]:
                raise SyntaxError(f'Unexpected token {sym} in state {state}')
            
            act, param = self.action[state][token_type]
            
            if act == 'S':  # Shift
                state_stack.append(param)
                # Push token value onto value stack
                value_stack.append(getattr(sym, 'value', sym.text if hasattr(sym, 'text') else sym))
                sym = self.lexer.next_token()
                
            elif act == 'R':  # Reduce
                lhs, length = self.rules[param]
                
                # Get values from stack for semantic action
                if length > 0:
                    vals = value_stack[-length:]
                else:
                    vals = []
                
                # Default: result = first value or None
                result = vals[0] if vals else None
                
                # Semantic action by rule
                rule_id = param
                if rule_id == 3:
                    result = vals[0] print("= %g", result)
                if rule_id == 4:
                    yyerrok
                if rule_id == 5:
                    result = vals[0]
                if rule_id == 6:
                    result = vals[0] + vals[2]
                if rule_id == 7:
                    result = vals[0] - vals[2]
                if rule_id == 8:
                    result = vals[0]
                if rule_id == 9:
                    result = vals[0] * vals[2]
                if rule_id == 10:
                    if (vals[2] == 0.0) {
                    yyerror("division by zero")
                    result = 0.0
                    } else {
                    result = vals[0] / vals[2]
                    }
                if rule_id == 11:
                    result = fmod(vals[0], vals[2])
                if rule_id == 12:
                    result = vals[0]
                if rule_id == 13:
                    result = pow(vals[0], vals[2])
                if rule_id == 14:
                    result = -vals[1]
                if rule_id == 15:
                    result = vals[0]
                if rule_id == 16:
                    result = vals[1]
                
                # Pop stacks
                for _ in range(length):
                    state_stack.pop()
                    value_stack.pop()
                
                # Push result and goto state
                top = state_stack[-1]
                if top in self.goto and lhs in self.goto[top]:
                    state_stack.append(self.goto[top][lhs])
                    value_stack.append(result)
                else:
                    raise SyntaxError(f'No goto for {lhs} from state {top}')
                    
            elif act == 'A':  # Accept
                return value_stack[-1] if len(value_stack) > 1 else None


# =============================================================================
# Combined Lexer + Parser Test Driver
# =============================================================================

class LexerAdapter:
    """Adapts a lexer to work with the parser.
    
    Usage:
        from lexer import Lexer, TokenType
        from parser import Parser, LexerAdapter
        
        adapter = LexerAdapter(Lexer('3 + 4 * 2'))
        parser = Parser(adapter)
        result = parser.parse()
    """
    def __init__(self, lexer):
        self.lexer = lexer
    
    def next_token(self):
        tok = self.lexer.next_token()
        # Return adapted token with string type name
        return AdaptedToken(tok)


class AdaptedToken:
    """Token adapter for parser compatibility."""
    def __init__(self, tok):
        # Convert enum to parser terminal names ('$' for EOF)
        raw_type = tok.type.name
        token_aliases = {
            'EOF': '$',
            'INTEGER_LITERAL': 'NUMBER',
            'INT_LITERAL': 'NUMBER',
            'NUM_LITERAL': 'NUMBER',
            'FLOAT_LITERAL': 'NUMBER',
        }
        self.type = token_aliases.get(raw_type, raw_type)
        self.text = tok.text
        self.pos = tok.pos
        # Extract numeric value for NUMBER tokens
        try:
            self.value = int(tok.text) if tok.text.isdigit() else tok.text
        except:
            self.value = tok.text


def parse_expression(expr: str, lexer_class=None):
    """Parse an expression string and return the result.
    
    Args:
        expr: The expression to parse
        lexer_class: Optional custom Lexer class (defaults to imported Lexer)
    
    Returns:
        The parse result (semantic value from reduction)
    
    Example:
        >>> parse_expression('3 + 4')
        7
    """
    if lexer_class is not None:
        LexerClass = lexer_class
    else:
        import importlib
        import importlib.util
        from pathlib import Path

        LexerClass = None
        # 1) Try normal module imports (both common naming conventions)
        for module_name in ('lexer', 'Lexer'):
            try:
                mod = importlib.import_module(module_name)
                if hasattr(mod, 'Lexer'):
                    LexerClass = getattr(mod, 'Lexer')
                    break
            except Exception:
                pass

        # 2) Try loading sibling files next to this parser file
        if LexerClass is None:
            base_dir = Path(__file__).resolve().parent if '__file__' in globals() else Path.cwd()
            for filename in ('lexer.py', 'Lexer.py'):
                path = base_dir / filename
                if not path.exists():
                    continue
                spec = importlib.util.spec_from_file_location(path.stem, str(path))
                if spec is None or spec.loader is None:
                    continue
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                if hasattr(mod, 'Lexer'):
                    LexerClass = getattr(mod, 'Lexer')
                    break

        if LexerClass is None:
            raise ImportError('Could not import Lexer. Checked modules lexer/Lexer and sibling files lexer.py/Lexer.py.')
    
    adapter = LexerAdapter(LexerClass(expr))
    parser = Parser(adapter)
    return parser.parse()


def test_parse(expr: str):
    """Test parsing an expression and print the result."""
    print(f'Parsing: {expr!r}')
    try:
        result = parse_expression(expr)
        print(f'  Result: {result}')
        return result
    except Exception as e:
        print(f'  Error: {e}')
        return None


if __name__ == '__main__':
    import sys
    print('=== OpenLexer Parser Test Driver ===')
    print()
    
    if len(sys.argv) > 1:
        for arg in sys.argv[1:]:
            test_parse(arg)
    else:
        _input = sys.stdin.read().strip()
        if _input:
            for line in _input.splitlines():
                test_parse(line)
        else:
            test_parse('3 + 4')
            test_parse('3 + 4 * 2')
