"""Lexer generated by OpenLexer"""

TOKEN_EOF, TOKEN_ERROR = 0, 1
TOKEN_NUMBER = 2
TOKEN_PLUS = 3
TOKEN_MINUS = 4
TOKEN_TIMES = 5
TOKEN_DIVIDE = 6
TOKEN_MOD = 7
TOKEN_POWER = 8
TOKEN_LPAREN = 9
TOKEN_RPAREN = 10
TOKEN_NEWLINE = 11

TOKEN_NAMES = {TOKEN_EOF: 'EOF', TOKEN_ERROR: 'ERROR', TOKEN_NUMBER: 'NUMBER', TOKEN_PLUS: 'PLUS', TOKEN_MINUS: 'MINUS', TOKEN_TIMES: 'TIMES', TOKEN_DIVIDE: 'DIVIDE', TOKEN_MOD: 'MOD', TOKEN_POWER: 'POWER', TOKEN_LPAREN: 'LPAREN', TOKEN_RPAREN: 'RPAREN', TOKEN_NEWLINE: 'NEWLINE'}

_TRANS = {
    0: [(0,8,1),(9,9,2),(10,10,3),(11,31,1),(32,32,2),(33,36,1),(37,37,4),(38,39,1),(40,40,5),(41,41,6),(42,42,7),(43,43,8),(44,44,1),(45,45,9),(46,46,1),(47,47,10),(48,57,11),(58,93,1),(94,94,12),(95,127,1),],
    2: [(9,9,19),(32,32,19),],
    11: [(46,46,13),(48,57,14),(69,69,15),(101,101,15),],
    13: [(48,57,18),],
    14: [(46,46,13),(48,57,14),(69,69,15),(101,101,15),],
    15: [(43,43,16),(45,45,16),(48,57,17),],
    16: [(48,57,17),],
    17: [(48,57,17),],
    18: [(48,57,18),(69,69,15),(101,101,15),],
    19: [(9,9,19),(32,32,19),],
}

_ACCEPT = {1: 11,2: 10,3: 9,4: 5,5: 7,6: 8,7: 3,8: 1,9: 2,10: 4,11: 0,12: 6,14: 0,17: 0,18: 0,19: 10,}

_RULE_TOKEN = {0: TOKEN_NUMBER,1: TOKEN_PLUS,2: TOKEN_MINUS,3: TOKEN_TIMES,4: TOKEN_DIVIDE,5: TOKEN_MOD,6: TOKEN_POWER,7: TOKEN_LPAREN,8: TOKEN_RPAREN,9: TOKEN_NEWLINE,10: None,11: None,}

class Lexer:
    def __init__(self, src): self.src, self.pos = src, 0

    def next_token(self):
        while self.pos < len(self.src):
            start, state, last_rule, last_pos = self.pos, 0, -1, self.pos
            while self.pos < len(self.src):
                cp, ns = ord(self.src[self.pos]), -1
                for lo, hi, tgt in _TRANS.get(state, []):
                    if lo <= cp <= hi: ns = tgt; break
                if ns < 0: break
                state = ns; self.pos += 1
                if state in _ACCEPT: last_rule, last_pos = _ACCEPT[state], self.pos
            if last_rule >= 0:
                self.pos = last_pos
                tok = _RULE_TOKEN.get(last_rule, TOKEN_ERROR)
                if tok is None: continue
                return (tok, self.src[start:last_pos])
            self.pos = start + 1
            return (TOKEN_ERROR, self.src[start:start+1])
        return (TOKEN_EOF, '')

    def tokenize(self):
        while True:
            tok = self.next_token()
            yield tok
            if tok[0] == TOKEN_EOF: break

def test(text):
    print(f'Input: "{text}"')
    for tok, val in Lexer(text).tokenize():
        print(f'  [{TOKEN_NAMES.get(tok, tok)}] "{val}"')

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        for arg in sys.argv[1:]: test(arg)
    else:
        import sys as _sys
        _input = _sys.stdin.read().strip()
        if _input:
            for line in _input.splitlines(): test(line)
        else: test('3 + 4 * 2'); test('(10 - 2) / 4')
