//! Code generation for parsers with semantic actions.

use crate::parsegen::lalr::{ParsingTable, Action};
use crate::parsegen::grammar::Grammar;
use crate::lexgen::codegen::TargetLanguage;
use crate::error::Result;

pub fn generate_parser(table: &ParsingTable, grammar: &Grammar, lang: TargetLanguage) -> Result<String> {
    match lang {
        TargetLanguage::C => generate_c(table, grammar),
        TargetLanguage::Java => generate_java(table, grammar),
        TargetLanguage::Python => generate_python(table, grammar),
    }
}

fn generate_c(table: &ParsingTable, grammar: &Grammar) -> Result<String> {
    let mut code = String::new();
    code.push_str("/* Generated by OpenLexer */\n");
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n\n");
    
    // Definitions
    code.push_str("#define STACK_SIZE 1024\n");
    code.push_str("typedef struct { int state; int value; } StackItem;\n");
    code.push_str("StackItem stack[STACK_SIZE];\n");
    code.push_str("int top = 0;\n\n");

    // Action Table Structure: 
    // We can't generate a sparse full matrix for C easily without 2D array.
    // For MVP: Linear search or simple 2D array if token count is small.
    // Let's use a flat list of transitions for each state to be safe.
    // Actually, generating a big `get_action(state, token)` function is easiest in C.
    
    code.push_str("void push(int state, int value) {\n");
    code.push_str("    if (top >= STACK_SIZE) { fprintf(stderr, \"Stack overflow\\n\"); exit(1); }\n");
    code.push_str("    top++;\n");
    code.push_str("    stack[top].state = state;\n");
    code.push_str("    stack[top].value = value;\n");
    code.push_str("}\n\n");
    
    code.push_str("int pop(int n) {\n");
    code.push_str("    top -= n;\n");
    code.push_str("    return (top >= 0) ? stack[top].state : 0;\n");
    code.push_str("}\n\n");

    // Action Lookup Function
    code.push_str("// Action: 0=Error, 1=Shift, 2=Reduce, 3=Accept\n");
    code.push_str("void get_action(int state, const char* token, int* type, int* param) {\n");
    code.push_str("    *type = 0; *param = 0;\n");
    
    for (state, actions) in &table.action {
        code.push_str(&format!("    if (state == {}) {{\n", state));
        for (term, act) in actions {
            let (t, p) = match act {
                Action::Shift(n) => (1, *n),
                Action::Reduce(n) => (2, *n),
                Action::Accept => (3, 0),
            };
            code.push_str(&format!("        if (strcmp(token, \"{}\") == 0) {{ *type = {}; *param = {}; return; }}\n", term, t, p));
        }
        code.push_str("    }\n");
    }
    code.push_str("}\n\n");

    // Goto Lookup Function
    code.push_str("int get_goto(int state, const char* lhs) {\n");
    for (state, gotos) in &table.goto {
        code.push_str(&format!("    if (state == {}) {{\n", state));
        for (nt, next) in gotos {
             code.push_str(&format!("        if (strcmp(lhs, \"{}\") == 0) return {};\n", nt, next));
        }
        code.push_str("    }\n");
    }
    code.push_str("    return -1;\n");
    code.push_str("}\n\n");

    // Rule Info
    code.push_str("void get_rule(int id, char** lhs, int* len) {\n");
    code.push_str("    switch(id) {\n");
    for (i, rule) in grammar.rules.iter().enumerate() {
        code.push_str(&format!("        case {}: *lhs = \"{}\"; *len = {}; break;\n", i, rule.lhs, rule.rhs.len()));
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("int yylval = 0;\n");
    code.push_str("void yyparse() {\n");
    code.push_str("    top = 0; stack[0].state = 0;\n");
    code.push_str("    char* sym = \"NUM\"; // TODO: Connect to Lexer\n");
    code.push_str("    int type, param;\n");
    code.push_str("    char* lhs;\n");
    code.push_str("    int len;\n\n");
    
    code.push_str("    while (1) {\n");
    code.push_str("        int state = stack[top].state;\n");
    code.push_str("        get_action(state, sym, &type, &param);\n\n");
    
    code.push_str("        if (type == 0) { fprintf(stderr, \"Syntax Error\\n\"); exit(1); }\n");
    code.push_str("        if (type == 1) { /* Shift */\n");
    code.push_str("            /* Simulate yylval logic: assumes lexer sets global yylval */\n");
    code.push_str("            push(param, yylval);\n");
    code.push_str("            /* sym = yylex(); */\n");
    code.push_str("        } else if (type == 2) { /* Reduce */\n");
    code.push_str("            int yyval = 0;\n");
    code.push_str("            get_rule(param, &lhs, &len);\n");
    code.push_str("            if (len > 0) yyval = stack[top - (len - 1)].value; /* Default $$=$1 */\n");
    code.push_str("            \n");
    code.push_str("            /* Semantic Actions */\n");
    code.push_str("            switch(param) {\n");
    for (i, rule) in grammar.rules.iter().enumerate() {
        if let Some(action) = &rule.action {
            let substituted = substitute_vars_c(action, rule.rhs.len());
            code.push_str(&format!("                case {}:\n", i));
            code.push_str(&format!("                    {{\n{}\n}}\n", substituted));
            code.push_str("                    break;\n");
        }
    }
    code.push_str("            }\n\n");
    code.push_str("            pop(len);\n");
    code.push_str("            int next_state = get_goto(stack[top].state, lhs);\n");
    code.push_str("            if (next_state == -1) { fprintf(stderr, \"Goto Error\\n\"); exit(1); }\n");
    code.push_str("            push(next_state, yyval);\n");
    code.push_str("        } else if (type == 3) { /* Accept */\n");
    code.push_str("            printf(\"Accept!\\n\");\n");
    code.push_str("            return;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    code.push_str("#ifndef PARSER_NO_MAIN\n");
    code.push_str("int main() { yyparse(); return 0; }\n");
    code.push_str("#endif\n");

    Ok(code)
}

fn substitute_vars_c(action: &str, rhs_len: usize) -> String {
    let mut out = String::new();
    let chars: Vec<char> = action.chars().collect();
    let mut i = 0;
    
    while i < chars.len() {
        if chars[i] == '$' {
            if i + 1 < chars.len() {
                if chars[i+1] == '$' {
                    out.push_str("yyval");
                    i += 2;
                } else if chars[i+1].is_ascii_digit() {
                    let mut j = i + 1;
                    while j < chars.len() && chars[j].is_ascii_digit() {
                        j += 1;
                    }
                    let num_str: String = chars[i+1..j].iter().collect();
                    if let Ok(n) = num_str.parse::<usize>() {
                        if n > 0 && n <= rhs_len {
                            // stack[top - (len - N)].value
                            let offset = rhs_len - n;
                            out.push_str(&format!("stack[top - {}].value", offset));
                        } else {
                            // Out of bounds or bad reference, keep as is?
                            // Or just emit stack ref anyway hoping for valid logic context
                             out.push_str("stack[top].value"); // Fallback
                        }
                    }
                    i = j;
                } else {
                    out.push('$');
                    i += 1;
                }
            } else {
                out.push('$');
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

fn generate_java(table: &ParsingTable, grammar: &Grammar) -> Result<String> {
    let mut code = String::new();
    code.push_str("import java.util.Stack;\n");
    code.push_str("import java.util.HashMap;\n\n");
    code.push_str("public class Parser {\n");
    code.push_str("    private static class Action {\n");
    code.push_str("        char type; // 'S', 'R', 'A', 'E'\n");
    code.push_str("        int param;\n");
    code.push_str("        Action(char t, int p) { type = t; param = p; }\n");
    code.push_str("    }\n\n");
    
    code.push_str("    private HashMap<Integer, HashMap<String, Action>> actionTable = new HashMap<>();\n");
    code.push_str("    private HashMap<Integer, HashMap<String, Integer>> gotoTable = new HashMap<>();\n");
    code.push_str("    private int[][] rules; // [lhs_id, rhs_len]\n");
    code.push_str("    // Register storage for calculator variables a-z\n");
    code.push_str("    private int[] regs = new int[26];\n\n");
    
    code.push_str("    public Parser() {\n");
    code.push_str("        initTables();\n");
    code.push_str("    }\n\n");

    code.push_str("    private void initTables() {\n");
    
    // Serialize Action Table
    for (state, actions) in &table.action {
         code.push_str(&format!("        actionTable.put({}, new HashMap<>());\n", state));
         for (term, act) in actions {
             let (t, p) = match act {
                 Action::Shift(n) => ('S', *n),
                 Action::Reduce(n) => ('R', *n),
                 Action::Accept => ('A', 0),
             };
             code.push_str(&format!("        actionTable.get({}).put(\"{}\", new Action('{}', {}));\n", state, term, t, p));
         }
    }
    
    // Serialize Goto Table
    for (state, gotos) in &table.goto {
        code.push_str(&format!("        gotoTable.put({}, new HashMap<>());\n", state));
         for (nt, next) in gotos {
             code.push_str(&format!("        gotoTable.get({}).put(\"{}\", {});\n", state, nt, next));
         }
    }

    // Serialize Rules info
    code.push_str("        rules = new int[][] {\n");
    for rule in &grammar.rules {
        // We need an ID for LHS string? For now just storing length. 
        // Real impl needs string map. For MVP using dummy 0 for LHS ID since we use string goto.
        code.push_str(&format!("            {{ 0, {} }}, // {} -> ...\n", rule.rhs.len(), rule.lhs));
    }
    code.push_str("        };\n");
    code.push_str("    }\n\n");
    
    code.push_str("    // Helper to get LHS string by rule index\n");
    code.push_str("    private String getLhs(int ruleId) {\n");
     code.push_str("        switch(ruleId) {\n");
    for (i, rule) in grammar.rules.iter().enumerate() {
        code.push_str(&format!("            case {}: return \"{}\";\n", i, rule.lhs));
    }
    code.push_str("            default: return \"\";\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    public int parse(Lexer lexer) {\n");
    code.push_str("        Stack<Integer> stack = new Stack<>();\n");
    code.push_str("        Stack<Integer> valueStack = new Stack<>();\n");
    code.push_str("        stack.push(0);\n");
    code.push_str("        valueStack.push(0);\n");
    code.push_str("        Token token = lexer.nextToken();\n");
    code.push_str("        String sym = token.type;\n");
    code.push_str("        \n");
    code.push_str("        while (true) {\n");
    code.push_str("            int state = stack.peek();\n");
    code.push_str("            if (!actionTable.containsKey(state) || !actionTable.get(state).containsKey(sym)) {\n");
    code.push_str("                throw new RuntimeException(\"Syntax Error\");\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            Action act = actionTable.get(state).get(sym);\n");
    code.push_str("            if (act.type == 'S') { // Shift\n");
    code.push_str("                stack.push(act.param);\n");
    code.push_str("                valueStack.push(token.value);\n");
    code.push_str("                token = lexer.nextToken();\n");
    code.push_str("                sym = token.type;\n");
    code.push_str("            } else if (act.type == 'R') { // Reduce\n");
    code.push_str("                int ruleId = act.param;\n");
    code.push_str("                int len = rules[ruleId][1];\n");
    code.push_str("                String lhs = getLhs(ruleId);\n");
    code.push_str("                \n");
    code.push_str("                // Get values from stack for semantic action\n");
    code.push_str("                int[] vals = new int[len];\n");
    code.push_str("                for (int i = len - 1; i >= 0; i--) {\n");
    code.push_str("                    vals[i] = valueStack.peek();\n");
    code.push_str("                    valueStack.pop();\n");
    code.push_str("                    stack.pop();\n");
    code.push_str("                }\n");
    code.push_str("                int result = (len > 0) ? vals[0] : 0;\n");
    code.push_str("                \n");
    code.push_str("                // Semantic Actions\n");
    code.push_str("                switch (ruleId) {\n");
    for (i, rule) in grammar.rules.iter().enumerate() {
        if let Some(action) = &rule.action {
            let translated = translate_action_java(action, rule.rhs.len());
            code.push_str(&format!("                    case {}:\n", i));
            for line in translated.lines() {
                if !line.trim().is_empty() {
                    code.push_str(&format!("                        {}\n", line.trim()));
                }
            }
            code.push_str("                        break;\n");
        }
    }
    code.push_str("                }\n");
    code.push_str("                \n");
    code.push_str("                int top = stack.peek();\n");
    code.push_str("                if (gotoTable.containsKey(top) && gotoTable.get(top).containsKey(lhs)) {\n");
    code.push_str("                    stack.push(gotoTable.get(top).get(lhs));\n");
    code.push_str("                    valueStack.push(result);\n");
    code.push_str("                }\n");
    code.push_str("            } else if (act.type == 'A') {\n");
    code.push_str("                return valueStack.peek();\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Token and Lexer interfaces (implement or use generated lexer)\n");
    code.push_str("    public interface Lexer {\n");
    code.push_str("        Token nextToken();\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    public static class Token {\n");
    code.push_str("        public String type;\n");
    code.push_str("        public int value;\n");
    code.push_str("        public Token(String type, int value) {\n");
    code.push_str("            this.type = type;\n");
    code.push_str("            this.value = value;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    Ok(code)
}

/// Translate Bison-style semantic action to Java.
/// Converts $$ to result, $1/$2/etc to vals[0]/vals[1]/etc.
fn translate_action_java(action: &str, rhs_len: usize) -> String {
    let mut out = String::new();
    let chars: Vec<char> = action.chars().collect();
    let mut i = 0;
    
    while i < chars.len() {
        if chars[i] == '$' && i + 1 < chars.len() {
            if chars[i + 1] == '$' {
                out.push_str("result");
                i += 2;
            } else if chars[i + 1].is_ascii_digit() {
                let mut j = i + 1;
                while j < chars.len() && chars[j].is_ascii_digit() {
                    j += 1;
                }
                let num_str: String = chars[i + 1..j].iter().collect();
                if let Ok(n) = num_str.parse::<usize>() {
                    if n > 0 && n <= rhs_len {
                        out.push_str(&format!("vals[{}]", n - 1));
                    } else {
                        out.push_str("0");  // Invalid reference
                    }
                }
                i = j;
            } else {
                out.push('$');
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    
    // Convert C patterns to Java
    out = out.replace("printf(", "System.out.printf(");
    out = out.replace("pow(", "(int)Math.pow(");
    
    // Remove C-specific tokens that have no Java equivalent
    out = out.replace("yyerrok", "/* yyerrok */");
    
    out
}

fn generate_python(table: &ParsingTable, grammar: &Grammar) -> Result<String> {
    let mut code = String::new();
    code.push_str("# Generated by OpenLexer\n\n");
    code.push_str("class Parser:\n");
    code.push_str("    def __init__(self, lexer):\n");
    code.push_str("        self.lexer = lexer\n");
    code.push_str("        self.action = {\n");
    
    // Serialize Action Table
    for (state, actions) in &table.action {
        code.push_str(&format!("            {}: {{", state));
        for (term, act) in actions {
            match act {
                Action::Shift(next) => code.push_str(&format!("'{}': ('S', {}), ", term, next)),
                Action::Reduce(rule) => code.push_str(&format!("'{}': ('R', {}), ", term, rule)),
                Action::Accept => code.push_str(&format!("'{}': ('A', 0), ", term)),
            }
        }
        code.push_str("},\n");
    }
    code.push_str("        }\n");

    code.push_str("        self.goto = {\n");
    for (state, gotos) in &table.goto {
        code.push_str(&format!("            {}: {{", state));
        for (nt, next) in gotos {
             code.push_str(&format!("'{}': {}, ", nt, next));
        }
        code.push_str("},\n");
    }
    code.push_str("        }\n");

    // LHS and RHS_LEN lookup for Reductions
    code.push_str("        self.rules = [\n");
    for rule in &grammar.rules {
        code.push_str(&format!("            ('{}', {}),\n", rule.lhs, rule.rhs.len()));
    }
    code.push_str("        ]\n\n");

    code.push_str("    def parse(self):\n");
    code.push_str("        state_stack = [0]\n");
    code.push_str("        value_stack = [None]  # Semantic values\n");
    code.push_str("        sym = self.lexer.next_token()\n");
    code.push_str("        \n");
    code.push_str("        while True:\n");
    code.push_str("            state = state_stack[-1]\n");
    code.push_str("            token_type = sym.type if hasattr(sym, 'type') else str(sym)\n");
    code.push_str("            \n");
    code.push_str("            if state not in self.action or token_type not in self.action[state]:\n");
    code.push_str("                raise SyntaxError(f'Unexpected token {sym} in state {state}')\n");
    code.push_str("            \n");
    code.push_str("            act, param = self.action[state][token_type]\n");
    code.push_str("            \n");
    code.push_str("            if act == 'S':  # Shift\n");
    code.push_str("                state_stack.append(param)\n");
    code.push_str("                # Push token value onto value stack\n");
    code.push_str("                value_stack.append(getattr(sym, 'value', sym.text if hasattr(sym, 'text') else sym))\n");
    code.push_str("                sym = self.lexer.next_token()\n");
    code.push_str("                \n");
    code.push_str("            elif act == 'R':  # Reduce\n");
    code.push_str("                lhs, length = self.rules[param]\n");
    code.push_str("                \n");
    code.push_str("                # Get values from stack for semantic action\n");
    code.push_str("                if length > 0:\n");
    code.push_str("                    vals = value_stack[-length:]\n");
    code.push_str("                else:\n");
    code.push_str("                    vals = []\n");
    code.push_str("                \n");
    code.push_str("                # Default: result = first value or None\n");
    code.push_str("                result = vals[0] if vals else None\n");
    code.push_str("                \n");
    code.push_str("                # Semantic action by rule\n");
    code.push_str("                rule_id = param\n");
    
    // Generate semantic actions
    for (i, rule) in grammar.rules.iter().enumerate() {
        if let Some(action) = &rule.action {
            let translated = translate_action_python(action, rule.rhs.len());
            code.push_str(&format!("                if rule_id == {}:\n", i));
            for line in translated.lines() {
                if !line.trim().is_empty() {
                    code.push_str(&format!("                    {}\n", line.trim()));
                }
            }
        }
    }
    
    code.push_str("                \n");
    code.push_str("                # Pop stacks\n");
    code.push_str("                for _ in range(length):\n");
    code.push_str("                    state_stack.pop()\n");
    code.push_str("                    value_stack.pop()\n");
    code.push_str("                \n");
    code.push_str("                # Push result and goto state\n");
    code.push_str("                top = state_stack[-1]\n");
    code.push_str("                if top in self.goto and lhs in self.goto[top]:\n");
    code.push_str("                    state_stack.append(self.goto[top][lhs])\n");
    code.push_str("                    value_stack.append(result)\n");
    code.push_str("                else:\n");
    code.push_str("                    raise SyntaxError(f'No goto for {lhs} from state {top}')\n");
    code.push_str("                    \n");
    code.push_str("            elif act == 'A':  # Accept\n");
    code.push_str("                return value_stack[-1] if len(value_stack) > 1 else None\n");
    
    Ok(code)
}

/// Translate Bison-style semantic action to Python.
/// Converts $$ to result, $1/$2/etc to vals[0]/vals[1]/etc.
fn translate_action_python(action: &str, rhs_len: usize) -> String {
    let mut out = String::new();
    let chars: Vec<char> = action.chars().collect();
    let mut i = 0;
    
    while i < chars.len() {
        if chars[i] == '$' && i + 1 < chars.len() {
            if chars[i + 1] == '$' {
                out.push_str("result");
                i += 2;
            } else if chars[i + 1].is_ascii_digit() {
                let mut j = i + 1;
                while j < chars.len() && chars[j].is_ascii_digit() {
                    j += 1;
                }
                let num_str: String = chars[i + 1..j].iter().collect();
                if let Ok(n) = num_str.parse::<usize>() {
                    if n > 0 && n <= rhs_len {
                        out.push_str(&format!("vals[{}]", n - 1));
                    } else {
                        out.push_str("None");  // Invalid reference
                    }
                }
                i = j;
            } else {
                out.push('$');
                i += 1;
            }
        } else if chars[i] == ';' {
            // Skip semicolons (C statement terminator)
            i += 1;
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    
    // Convert some common C patterns to Python
    out = out.replace("printf(", "print(");
    out = out.replace("%d", "{}");
    out = out.replace("\\n", "");
    
    out
}
