name: Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup toolchain for wasm
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      
      - name: Install mdBook
        run: |
          wget -qO- https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      
      - name: Build WASM app
        run: ./trunk build --release --public-url $public_url web/index.html
        env:
          public_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
      
      - name: Build documentation
        run: ./mdbook build docs
      
      - name: Copy docs to dist
        run: cp -r docs/book dist/docs
      
      - name: Deploy
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
